/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Thu Mar  9 21:05:03 PST 2017
 * 
 */
#include "bluesim_primitives.h"
#include "mkNextFloorStop.h"


/* String declarations */
static std::string const __str_literal_7("----------------------------------------------", 46u);
static std::string const __str_literal_11("Expected=%d, Your answer=%d", 27u);
static std::string const __str_literal_13("FAILED!", 7u);
static std::string const __str_literal_3("False", 5u);
static std::string const __str_literal_6("Floor:%d floor_des           = %s", 33u);
static std::string const __str_literal_5("Floor:%d floor_down_pressed  = %s", 33u);
static std::string const __str_literal_4("Floor:%d floor_up_pressed    = %s", 33u);
static std::string const __str_literal_12("PASS %d\n______________________________________________________________________",
					  78u);
static std::string const __str_literal_1("PASSED", 6u);
static std::string const __str_literal_2("True", 4u);
static std::string const __str_literal_8("currentFloor=%d", 15u);
static std::string const __str_literal_9("moving direction: DOWN", 22u);
static std::string const __str_literal_10("moving direction: UP", 20u);


/* Constructor */
MOD_mkNextFloorStop::MOD_mkNextFloorStop(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_cycle(simHdl, "cycle", this, 32u, 0u, (tUInt8)0u),
    INST_testTb(simHdl, "testTb", this),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 4u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkNextFloorStop::init_symbols_0()
{
  init_symbol(&symbols[0u], "cycle", SYM_MODULE, &INST_cycle);
  init_symbol(&symbols[1u], "RL_test", SYM_RULE);
  init_symbol(&symbols[2u], "testTb", SYM_MODULE, &INST_testTb);
  init_symbol(&symbols[3u], "x__h136", SYM_DEF, &DEF_x__h136, 32u);
}


/* Rule actions */

void MOD_mkNextFloorStop::RL_test()
{
  tUInt32 DEF_x__h19783;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d23;
  tUInt8 DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128___d9;
  tUInt8 DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211;
  tUInt8 DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d227;
  tUInt8 DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d231;
  tUInt8 DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236;
  tUInt8 DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d239;
  tUInt8 DEF_NOT_cycle_EQ_0___d7;
  tUInt8 DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d242;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d27;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d31;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d54;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d40;
  tUInt8 DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d62;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d103;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d105;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d107;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d124;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d115;
  tUInt8 DEF_NOT_cycle_EQ_128___d8;
  tUInt8 DEF_NOT_testTb_getObj_0_BIT_0_1___d228;
  tUInt8 DEF_NOT_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT__ETC___d234;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d85;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d26;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d39;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d30;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d53;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d29;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d25;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d35;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d47;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d73;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d56;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d106;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d104;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d110;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d111;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d114;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d113;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d123;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d121;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d142;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d126;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d150;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d133;
  tUInt8 DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d132;
  tUInt32 DEF_x__h394;
  tUInt32 DEF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_testTb_ge_ETC___d16;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d33;
  tUInt8 DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d58;
  tUInt32 DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d61;
  tUInt32 DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d45;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d108;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d128;
  tUInt32 DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d131;
  tUInt32 DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d120;
  tUInt32 DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d160;
  tUInt32 DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d95;
  tUInt8 DEF_testTb_getObj_0_BIT_33_4_OR_testTb_getObj_0_BI_ETC___d172;
  tUInt8 DEF_testTb_getObj_0_BIT_34_8_OR_testTb_getObj_0_BI_ETC___d171;
  tUInt8 DEF_testTb_getObj_0_BIT_35_2_OR_testTb_getObj_0_BI_ETC___d170;
  tUInt32 DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d199;
  tUInt8 DEF_testTb_getObj_0_BIT_34_8_OR_testTb_getObj_0_BI_ETC___d185;
  tUInt32 DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d207;
  tUInt32 DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d181;
  tUInt8 DEF_testTb_getObj_0_BIT_39_3_OR_testTb_getObj_0_BI_ETC___d183;
  tUInt32 DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d193;
  tUInt8 DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_33_4_9_NOT_tes_ETC___d101;
  tUInt8 DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_36_6_4_NOT_tes_ETC___d98;
  tUInt8 DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_39_3_4_NOT_tes_ETC___d164;
  tUInt8 DEF_NOT_testTb_getObj_0_BIT_38_1___d52;
  tUInt8 DEF_NOT_testTb_getObj_0_BIT_37_8___d49;
  tUInt8 DEF_NOT_testTb_getObj_0_BIT_36_6___d64;
  tUInt8 DEF_NOT_testTb_getObj_0_BIT_35_2___d38;
  tUInt8 DEF_NOT_testTb_getObj_0_BIT_34_8___d36;
  tUInt8 DEF_NOT_testTb_getObj_0_BIT_33_4___d69;
  tUInt8 DEF_NOT_testTb_getObj_0_BIT_41_8___d134;
  tUInt8 DEF_NOT_testTb_getObj_0_BIT_40_0___d81;
  tUInt8 DEF_NOT_testTb_getObj_0_BIT_39_3___d84;
  tUInt32 DEF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_testTb_ETC___d18;
  tUInt8 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d22;
  tUInt8 DEF_testTb_getObj_0_BIT_0___d11;
  tUInt8 DEF_testTb_getObj_0_BIT_32___d12;
  tUInt8 DEF_testTb_getObj_0_BIT_33___d24;
  tUInt8 DEF_testTb_getObj_0_BIT_34___d28;
  tUInt8 DEF_testTb_getObj_0_BIT_35___d32;
  tUInt8 DEF_testTb_getObj_0_BIT_36___d46;
  tUInt8 DEF_testTb_getObj_0_BIT_37___d48;
  tUInt8 DEF_testTb_getObj_0_BIT_38___d51;
  tUInt8 DEF_testTb_getObj_0_BIT_39___d83;
  tUInt8 DEF_testTb_getObj_0_BIT_40___d80;
  tUInt8 DEF_testTb_getObj_0_BIT_41___d78;
  tUInt32 DEF_testTb_getObj_0_BITS_32_TO_1___d13;
  tUInt64 DEF_testTb_getObj___d10;
  tUInt32 DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21;
  tUInt32 DEF_signed_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NE_ETC___d224;
  tUInt32 DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT_IF_I_ETC___d168;
  tUInt32 DEF_signed_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF__ETC___d232;
  tUInt32 DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_IF_testT_ETC___d208;
  tUInt32 DEF_signed_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF__ETC___d233;
  tUInt32 DEF_signed_0___d212;
  tUInt32 DEF_signed_1___d216;
  tUInt32 DEF_signed_2___d220;
  tUInt8 DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT_IF_I_ETC___d209;
  tUInt64 DEF_AVMeth_testTb_getObj;
  DEF_signed_2___d220 = 2u;
  DEF_signed_1___d216 = 1u;
  DEF_signed_0___d212 = 0u;
  DEF_x__h136 = INST_cycle.METH_read();
  DEF_cycle_EQ_128___d3 = DEF_x__h136 == 128u;
  DEF_cycle_EQ_0___d2 = DEF_x__h136 == 0u;
  DEF_NOT_cycle_EQ_128___d8 = !DEF_cycle_EQ_128___d3;
  DEF_NOT_cycle_EQ_0___d7 = !DEF_cycle_EQ_0___d2;
  DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128___d9 = DEF_NOT_cycle_EQ_0___d7 && DEF_NOT_cycle_EQ_128___d8;
  DEF_x__h19783 = DEF_x__h136 + 1u;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_cycle_EQ_128___d3)
      dollar_display(sim_hdl, this, "s", &__str_literal_1);
    if (DEF_cycle_EQ_128___d3)
      dollar_finish(sim_hdl, "32", 1u);
  }
  if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128___d9)
    DEF_AVMeth_testTb_getObj = INST_testTb.METH_getObj();
  DEF_testTb_getObj___d10 = DEF_AVMeth_testTb_getObj;
  DEF_testTb_getObj_0_BITS_32_TO_1___d13 = (tUInt32)(DEF_testTb_getObj___d10 >> 1u);
  DEF_testTb_getObj_0_BIT_41___d78 = (tUInt8)(DEF_testTb_getObj___d10 >> 41u);
  DEF_testTb_getObj_0_BIT_40___d80 = (tUInt8)((tUInt8)1u & (DEF_testTb_getObj___d10 >> 40u));
  DEF_testTb_getObj_0_BIT_39___d83 = (tUInt8)((tUInt8)1u & (DEF_testTb_getObj___d10 >> 39u));
  DEF_testTb_getObj_0_BIT_38___d51 = (tUInt8)((tUInt8)1u & (DEF_testTb_getObj___d10 >> 38u));
  DEF_testTb_getObj_0_BIT_37___d48 = (tUInt8)((tUInt8)1u & (DEF_testTb_getObj___d10 >> 37u));
  DEF_testTb_getObj_0_BIT_36___d46 = (tUInt8)((tUInt8)1u & (DEF_testTb_getObj___d10 >> 36u));
  DEF_testTb_getObj_0_BIT_35___d32 = (tUInt8)((tUInt8)1u & (DEF_testTb_getObj___d10 >> 35u));
  DEF_testTb_getObj_0_BIT_34___d28 = (tUInt8)((tUInt8)1u & (DEF_testTb_getObj___d10 >> 34u));
  DEF_testTb_getObj_0_BIT_33___d24 = (tUInt8)((tUInt8)1u & (DEF_testTb_getObj___d10 >> 33u));
  DEF_testTb_getObj_0_BIT_32___d12 = (tUInt8)((tUInt8)1u & (DEF_testTb_getObj___d10 >> 32u));
  DEF_testTb_getObj_0_BIT_0___d11 = (tUInt8)((tUInt8)1u & DEF_testTb_getObj___d10);
  DEF_NOT_testTb_getObj_0_BIT_39_3___d84 = !DEF_testTb_getObj_0_BIT_39___d83;
  DEF_NOT_testTb_getObj_0_BIT_40_0___d81 = !DEF_testTb_getObj_0_BIT_40___d80;
  DEF_NOT_testTb_getObj_0_BIT_41_8___d134 = !DEF_testTb_getObj_0_BIT_41___d78;
  DEF_NOT_testTb_getObj_0_BIT_33_4___d69 = !DEF_testTb_getObj_0_BIT_33___d24;
  DEF_NOT_testTb_getObj_0_BIT_34_8___d36 = !DEF_testTb_getObj_0_BIT_34___d28;
  DEF_NOT_testTb_getObj_0_BIT_36_6___d64 = !DEF_testTb_getObj_0_BIT_36___d46;
  DEF_NOT_testTb_getObj_0_BIT_35_2___d38 = !DEF_testTb_getObj_0_BIT_35___d32;
  DEF_NOT_testTb_getObj_0_BIT_37_8___d49 = !DEF_testTb_getObj_0_BIT_37___d48;
  DEF_NOT_testTb_getObj_0_BIT_38_1___d52 = !DEF_testTb_getObj_0_BIT_38___d51;
  DEF_IF_testTb_getObj_0_BIT_39_3_THEN_STR_True_ELSE_ETC___d213 = DEF_testTb_getObj_0_BIT_39___d83 ? __str_literal_2 : __str_literal_3;
  DEF_IF_testTb_getObj_0_BIT_40_0_THEN_STR_True_ELSE_ETC___d217 = DEF_testTb_getObj_0_BIT_40___d80 ? __str_literal_2 : __str_literal_3;
  DEF_IF_testTb_getObj_0_BIT_41_8_THEN_STR_True_ELSE_ETC___d221 = DEF_testTb_getObj_0_BIT_41___d78 ? __str_literal_2 : __str_literal_3;
  DEF_IF_testTb_getObj_0_BIT_38_1_THEN_STR_True_ELSE_ETC___d222 = DEF_testTb_getObj_0_BIT_38___d51 ? __str_literal_2 : __str_literal_3;
  DEF_IF_testTb_getObj_0_BIT_37_8_THEN_STR_True_ELSE_ETC___d218 = DEF_testTb_getObj_0_BIT_37___d48 ? __str_literal_2 : __str_literal_3;
  DEF_IF_testTb_getObj_0_BIT_36_6_THEN_STR_True_ELSE_ETC___d214 = DEF_testTb_getObj_0_BIT_36___d46 ? __str_literal_2 : __str_literal_3;
  DEF_IF_testTb_getObj_0_BIT_35_2_THEN_STR_True_ELSE_ETC___d223 = DEF_testTb_getObj_0_BIT_35___d32 ? __str_literal_2 : __str_literal_3;
  DEF_IF_testTb_getObj_0_BIT_33_4_THEN_STR_True_ELSE_ETC___d215 = DEF_testTb_getObj_0_BIT_33___d24 ? __str_literal_2 : __str_literal_3;
  DEF_IF_testTb_getObj_0_BIT_34_8_THEN_STR_True_ELSE_ETC___d219 = DEF_testTb_getObj_0_BIT_34___d28 ? __str_literal_2 : __str_literal_3;
  DEF_testTb_getObj_0_BIT_39_3_OR_testTb_getObj_0_BI_ETC___d183 = DEF_testTb_getObj_0_BIT_39___d83 || DEF_testTb_getObj_0_BIT_33___d24;
  DEF_testTb_getObj_0_BIT_34_8_OR_testTb_getObj_0_BI_ETC___d185 = DEF_testTb_getObj_0_BIT_34___d28 || DEF_testTb_getObj_0_BIT_40___d80;
  DEF_testTb_getObj_0_BIT_35_2_OR_testTb_getObj_0_BI_ETC___d170 = DEF_testTb_getObj_0_BIT_35___d32 || DEF_testTb_getObj_0_BIT_38___d51;
  DEF_testTb_getObj_0_BIT_34_8_OR_testTb_getObj_0_BI_ETC___d171 = DEF_testTb_getObj_0_BIT_34___d28 || DEF_testTb_getObj_0_BIT_37___d48;
  DEF_testTb_getObj_0_BIT_33_4_OR_testTb_getObj_0_BI_ETC___d172 = DEF_testTb_getObj_0_BIT_33___d24 || DEF_testTb_getObj_0_BIT_39___d83;
  DEF_x__h394 = DEF_testTb_getObj_0_BIT_32___d12 ? -DEF_testTb_getObj_0_BITS_32_TO_1___d13 : DEF_testTb_getObj_0_BITS_32_TO_1___d13;
  DEF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_testTb_ge_ETC___d16 = DEF_x__h394 % 3u;
  DEF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_testTb_ETC___d18 = DEF_testTb_getObj_0_BIT_32___d12 ? -DEF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_testTb_ge_ETC___d16 : DEF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_testTb_ge_ETC___d16;
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21 = (tUInt8)(DEF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_testTb_ETC___d18 >> 31u) ? -DEF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_testTb_ETC___d18 : DEF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_testTb_ETC___d18;
  DEF_signed_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NE_ETC___d224 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21;
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d22 = (tUInt8)(DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21 >> 31u);
  switch (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21) {
  case 0u:
    DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_39_3_4_NOT_tes_ETC___d164 = DEF_NOT_testTb_getObj_0_BIT_39_3___d84;
    break;
  case 1u:
    DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_39_3_4_NOT_tes_ETC___d164 = DEF_NOT_testTb_getObj_0_BIT_40_0___d81;
    break;
  case 2u:
    DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_39_3_4_NOT_tes_ETC___d164 = DEF_NOT_testTb_getObj_0_BIT_41_8___d134;
    break;
  default:
    DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_39_3_4_NOT_tes_ETC___d164 = (tUInt8)0u;
  }
  switch (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21) {
  case 0u:
    DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_36_6_4_NOT_tes_ETC___d98 = DEF_NOT_testTb_getObj_0_BIT_36_6___d64;
    break;
  case 1u:
    DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_36_6_4_NOT_tes_ETC___d98 = DEF_NOT_testTb_getObj_0_BIT_37_8___d49;
    break;
  case 2u:
    DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_36_6_4_NOT_tes_ETC___d98 = DEF_NOT_testTb_getObj_0_BIT_38_1___d52;
    break;
  default:
    DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_36_6_4_NOT_tes_ETC___d98 = (tUInt8)0u;
  }
  switch (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21) {
  case 0u:
    DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_33_4_9_NOT_tes_ETC___d101 = DEF_NOT_testTb_getObj_0_BIT_33_4___d69;
    break;
  case 1u:
    DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_33_4_9_NOT_tes_ETC___d101 = DEF_NOT_testTb_getObj_0_BIT_34_8___d36;
    break;
  case 2u:
    DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_33_4_9_NOT_tes_ETC___d101 = DEF_NOT_testTb_getObj_0_BIT_35_2___d38;
    break;
  default:
    DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_33_4_9_NOT_tes_ETC___d101 = (tUInt8)0u;
  }
  switch (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21) {
  case 0u:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d193 = DEF_testTb_getObj_0_BIT_33_4_OR_testTb_getObj_0_BI_ETC___d172 ? 0u : (DEF_testTb_getObj_0_BIT_34_8_OR_testTb_getObj_0_BI_ETC___d185 ? 1u : (DEF_testTb_getObj_0_BIT_35_2_OR_testTb_getObj_0_BI_ETC___d170 ? 2u : (DEF_testTb_getObj_0_BIT_37___d48 ? 1u : 0u)));
    break;
  case 1u:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d193 = DEF_testTb_getObj_0_BIT_34_8_OR_testTb_getObj_0_BI_ETC___d185 ? 1u : (DEF_testTb_getObj_0_BIT_35_2_OR_testTb_getObj_0_BI_ETC___d170 ? 2u : 1u);
    break;
  default:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d193 = 2u;
  }
  switch (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21) {
  case 2u:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d181 = DEF_testTb_getObj_0_BIT_35_2_OR_testTb_getObj_0_BI_ETC___d170 ? 2u : (DEF_testTb_getObj_0_BIT_34_8_OR_testTb_getObj_0_BI_ETC___d171 ? 1u : (DEF_testTb_getObj_0_BIT_33_4_OR_testTb_getObj_0_BI_ETC___d172 ? 0u : (DEF_testTb_getObj_0_BIT_40___d80 ? 1u : 2u)));
    break;
  case 1u:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d181 = DEF_testTb_getObj_0_BIT_34_8_OR_testTb_getObj_0_BI_ETC___d171 ? 1u : (DEF_testTb_getObj_0_BIT_33_4_OR_testTb_getObj_0_BI_ETC___d172 ? 0u : 1u);
    break;
  default:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d181 = 0u;
  }
  switch (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21) {
  case 0u:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d207 = DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d193;
    break;
  case 1u:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d207 = DEF_testTb_getObj_0_BIT_40___d80 || DEF_testTb_getObj_0_BIT_34___d28 ? DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21 : (DEF_testTb_getObj_0_BIT_38___d51 || DEF_testTb_getObj_0_BIT_35___d32 ? DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d193 : (DEF_testTb_getObj_0_BIT_39_3_OR_testTb_getObj_0_BI_ETC___d183 ? DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d181 : DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d193));
    break;
  case 2u:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d207 = DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d181;
    break;
  default:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d207 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21;
  }
  switch (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21) {
  case 2u:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d199 = DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d181;
    break;
  case 1u:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d199 = DEF_testTb_getObj_0_BIT_37___d48 || DEF_testTb_getObj_0_BIT_34___d28 ? DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21 : (DEF_testTb_getObj_0_BIT_39_3_OR_testTb_getObj_0_BI_ETC___d183 ? DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d181 : (DEF_testTb_getObj_0_BIT_38___d51 ? DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d193 : DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d181));
    break;
  case 0u:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d199 = DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d193;
    break;
  default:
    DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d199 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21;
  }
  DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_IF_testT_ETC___d208 = DEF_testTb_getObj_0_BIT_0___d11 ? DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d199 : DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d207;
  DEF_signed_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF__ETC___d233 = DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_IF_testT_ETC___d208;
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d30 = primSLT8(1u,
									  32u,
									  (tUInt32)(DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21),
									  32u,
									  2u);
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d53 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d30 || DEF_NOT_testTb_getObj_0_BIT_38_1___d52;
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d39 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d30 || DEF_NOT_testTb_getObj_0_BIT_35_2___d38;
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d26 = primSLT8(1u,
									  32u,
									  (tUInt32)(DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21),
									  32u,
									  1u);
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d85 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d22 || DEF_NOT_testTb_getObj_0_BIT_39_3___d84;
  DEF_NOT_testTb_getObj_0_BIT_0_1___d228 = !DEF_testTb_getObj_0_BIT_0___d11;
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d107 = primSLE8(1u,
									   32u,
									   (tUInt32)(DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21),
									   32u,
									   0u);
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d128 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d107 && DEF_testTb_getObj_0_BIT_39___d83;
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d108 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d107 && DEF_testTb_getObj_0_BIT_33___d24;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d113 = !DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d107;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d123 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d113 || DEF_NOT_testTb_getObj_0_BIT_39_3___d84;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d114 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d113 || DEF_NOT_testTb_getObj_0_BIT_33_4___d69;
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d105 = primSLE8(1u,
									   32u,
									   (tUInt32)(DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21),
									   32u,
									   1u);
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d126 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d105 && DEF_testTb_getObj_0_BIT_40___d80;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d111 = !DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d105;
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d106 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d105 && DEF_testTb_getObj_0_BIT_34___d28;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d115 = (DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d111 || DEF_NOT_testTb_getObj_0_BIT_34_8___d36) && DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d114;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d124 = (DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d111 || DEF_NOT_testTb_getObj_0_BIT_40_0___d81) && DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d123;
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d103 = primSLE8(1u,
									   32u,
									   (tUInt32)(DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21),
									   32u,
									   2u);
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d133 = !DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d103;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d150 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d133 || DEF_NOT_testTb_getObj_0_BIT_38_1___d52;
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d121 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d103 && DEF_testTb_getObj_0_BIT_41___d78;
  DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d131 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d121 && DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d124 ? 2u : (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d126 && DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d123 ? 1u : (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d128 ? 0u : DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21));
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d142 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d121 || (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d126 || DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d128);
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d104 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d103 && DEF_testTb_getObj_0_BIT_35___d32;
  DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d120 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d104 && DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d115 ? 2u : (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d106 && DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d114 ? 1u : (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d108 ? 0u : DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21));
  DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d132 = primSLE8(1u,
									   32u,
									   (tUInt32)(DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d120),
									   32u,
									   (tUInt32)(DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d131));
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d110 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d104 || (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d106 || DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d108);
  DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d160 = DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d110 && (DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d132 || ((DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d133 || DEF_NOT_testTb_getObj_0_BIT_41_8___d134) && DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d124)) ? DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d120 : ((((DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d133 || DEF_NOT_testTb_getObj_0_BIT_35_2___d38) && DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d115) && DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d142) || ((DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d110 && DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d142) && !DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d132) ? DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d131 : ((DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d107 && DEF_testTb_getObj_0_BIT_36___d46) && ((DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d111 || DEF_NOT_testTb_getObj_0_BIT_37_8___d49) && DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d150) ? 0u : ((DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d105 && DEF_testTb_getObj_0_BIT_37___d48) && DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d150 ? 1u : (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d103 && DEF_testTb_getObj_0_BIT_38___d51 ? 2u : DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21))));
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d40 = (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d26 || DEF_NOT_testTb_getObj_0_BIT_34_8___d36) && DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d39;
  DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d54 = (DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d26 || DEF_NOT_testTb_getObj_0_BIT_37_8___d49) && DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d53;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d27 = !DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d26;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d56 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d27 && DEF_testTb_getObj_0_BIT_37___d48;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d29 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d27 && DEF_testTb_getObj_0_BIT_34___d28;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d31 = !DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d30;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d58 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d31 && DEF_testTb_getObj_0_BIT_38___d51;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d33 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d31 && DEF_testTb_getObj_0_BIT_35___d32;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d23 = !DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d22;
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d47 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d23 && DEF_testTb_getObj_0_BIT_36___d46;
  DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d61 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d47 && DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d54 ? 0u : (DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d56 && DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d53 ? 1u : (DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d58 ? 2u : DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21));
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d73 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d47 || (DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d56 || DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d58);
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d25 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d23 && DEF_testTb_getObj_0_BIT_33___d24;
  DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d45 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d25 && DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d40 ? 0u : (DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d29 && DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d39 ? 1u : (DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d33 ? 2u : DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21));
  DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d35 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d25 || (DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d29 || DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d33);
  DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d62 = primSLT8(1u,
									  32u,
									  (tUInt32)(DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d45),
									  32u,
									  (tUInt32)(DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d61));
  DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d95 = DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d35 && (!DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d62 || ((DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d22 || DEF_NOT_testTb_getObj_0_BIT_36_6___d64) && DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d54)) ? DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d45 : ((((DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d22 || DEF_NOT_testTb_getObj_0_BIT_33_4___d69) && DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d40) && DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d73) || ((DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d35 && DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d73) && DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d62) ? DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d61 : ((DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d31 && DEF_testTb_getObj_0_BIT_41___d78) && ((DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d26 || DEF_NOT_testTb_getObj_0_BIT_40_0___d81) && DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d85) ? 2u : ((DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d27 && DEF_testTb_getObj_0_BIT_40___d80) && DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d85 ? 1u : (DEF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_ETC___d23 && DEF_testTb_getObj_0_BIT_39___d83 ? 0u : DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21))));
  DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT_IF_I_ETC___d168 = DEF_testTb_getObj_0_BIT_0___d11 ? ((DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d95 == DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21 && DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_36_6_4_NOT_tes_ETC___d98) && DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_33_4_9_NOT_tes_ETC___d101 ? DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d160 : DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d95) : ((DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d160 == DEF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF_tes_ETC___d21 && DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_39_3_4_NOT_tes_ETC___d164) && DEF_SEL_ARR_NOT_testTb_getObj_0_BIT_33_4_9_NOT_tes_ETC___d101 ? DEF_IF_NOT_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_ETC___d95 : DEF_IF_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NEG_IF__ETC___d160);
  DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT_IF_I_ETC___d209 = DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT_IF_I_ETC___d168 == DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_IF_testT_ETC___d208;
  DEF_signed_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF__ETC___d232 = DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT_IF_I_ETC___d168;
  DEF_NOT_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT__ETC___d234 = !DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT_IF_I_ETC___d209;
  DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d242 = DEF_NOT_cycle_EQ_0___d7 && (DEF_NOT_cycle_EQ_128___d8 && (DEF_NOT_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT__ETC___d234 && DEF_NOT_testTb_getObj_0_BIT_0_1___d228));
  DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d239 = DEF_NOT_cycle_EQ_0___d7 && (DEF_NOT_cycle_EQ_128___d8 && (DEF_NOT_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT__ETC___d234 && DEF_testTb_getObj_0_BIT_0___d11));
  DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236 = DEF_NOT_cycle_EQ_0___d7 && (DEF_NOT_cycle_EQ_128___d8 && DEF_NOT_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT__ETC___d234);
  DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d231 = DEF_NOT_cycle_EQ_0___d7 && (DEF_NOT_cycle_EQ_128___d8 && (DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT_IF_I_ETC___d209 && DEF_NOT_testTb_getObj_0_BIT_0_1___d228));
  DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d227 = DEF_NOT_cycle_EQ_0___d7 && (DEF_NOT_cycle_EQ_128___d8 && (DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT_IF_I_ETC___d209 && DEF_testTb_getObj_0_BIT_0___d11));
  DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211 = DEF_NOT_cycle_EQ_0___d7 && (DEF_NOT_cycle_EQ_128___d8 && DEF_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF_NOT_IF_I_ETC___d209);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_4,
		     DEF_signed_0___d212,
		     &DEF_IF_testTb_getObj_0_BIT_39_3_THEN_STR_True_ELSE_ETC___d213);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_5,
		     DEF_signed_0___d212,
		     &DEF_IF_testTb_getObj_0_BIT_36_6_THEN_STR_True_ELSE_ETC___d214);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_6,
		     DEF_signed_0___d212,
		     &DEF_IF_testTb_getObj_0_BIT_33_4_THEN_STR_True_ELSE_ETC___d215);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl, this, "s", &__str_literal_7);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_4,
		     DEF_signed_1___d216,
		     &DEF_IF_testTb_getObj_0_BIT_40_0_THEN_STR_True_ELSE_ETC___d217);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_5,
		     DEF_signed_1___d216,
		     &DEF_IF_testTb_getObj_0_BIT_37_8_THEN_STR_True_ELSE_ETC___d218);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_6,
		     DEF_signed_1___d216,
		     &DEF_IF_testTb_getObj_0_BIT_34_8_THEN_STR_True_ELSE_ETC___d219);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl, this, "s", &__str_literal_7);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_4,
		     DEF_signed_2___d220,
		     &DEF_IF_testTb_getObj_0_BIT_41_8_THEN_STR_True_ELSE_ETC___d221);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_5,
		     DEF_signed_2___d220,
		     &DEF_IF_testTb_getObj_0_BIT_38_1_THEN_STR_True_ELSE_ETC___d222);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_6,
		     DEF_signed_2___d220,
		     &DEF_IF_testTb_getObj_0_BIT_35_2_THEN_STR_True_ELSE_ETC___d223);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl, this, "s", &__str_literal_7);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl,
		     this,
		     "s,-32",
		     &__str_literal_8,
		     DEF_signed_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NE_ETC___d224);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d227)
      dollar_display(sim_hdl, this, "s", &__str_literal_9);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d231)
      dollar_display(sim_hdl, this, "s", &__str_literal_10);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32",
		     &__str_literal_11,
		     DEF_signed_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF__ETC___d232,
		     DEF_signed_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF__ETC___d233);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_IF_tes_ETC___d211)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_12, DEF_x__h136);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl, this, "s", &__str_literal_13);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_4,
		     DEF_signed_0___d212,
		     &DEF_IF_testTb_getObj_0_BIT_39_3_THEN_STR_True_ELSE_ETC___d213);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_5,
		     DEF_signed_0___d212,
		     &DEF_IF_testTb_getObj_0_BIT_36_6_THEN_STR_True_ELSE_ETC___d214);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_6,
		     DEF_signed_0___d212,
		     &DEF_IF_testTb_getObj_0_BIT_33_4_THEN_STR_True_ELSE_ETC___d215);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl, this, "s", &__str_literal_7);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_4,
		     DEF_signed_1___d216,
		     &DEF_IF_testTb_getObj_0_BIT_40_0_THEN_STR_True_ELSE_ETC___d217);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_5,
		     DEF_signed_1___d216,
		     &DEF_IF_testTb_getObj_0_BIT_37_8_THEN_STR_True_ELSE_ETC___d218);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_6,
		     DEF_signed_1___d216,
		     &DEF_IF_testTb_getObj_0_BIT_34_8_THEN_STR_True_ELSE_ETC___d219);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl, this, "s", &__str_literal_7);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_4,
		     DEF_signed_2___d220,
		     &DEF_IF_testTb_getObj_0_BIT_41_8_THEN_STR_True_ELSE_ETC___d221);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_5,
		     DEF_signed_2___d220,
		     &DEF_IF_testTb_getObj_0_BIT_38_1_THEN_STR_True_ELSE_ETC___d222);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,s",
		     &__str_literal_6,
		     DEF_signed_2___d220,
		     &DEF_IF_testTb_getObj_0_BIT_35_2_THEN_STR_True_ELSE_ETC___d223);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl, this, "s", &__str_literal_7);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl,
		     this,
		     "s,-32",
		     &__str_literal_8,
		     DEF_signed_IF_IF_testTb_getObj_0_BIT_32_2_THEN_NE_ETC___d224);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d239)
      dollar_display(sim_hdl, this, "s", &__str_literal_9);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d242)
      dollar_display(sim_hdl, this, "s", &__str_literal_10);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32",
		     &__str_literal_11,
		     DEF_signed_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF__ETC___d232,
		     DEF_signed_IF_testTb_getObj_0_BIT_0_1_THEN_IF_IF__ETC___d233);
    if (DEF_NOT_cycle_EQ_0_AND_NOT_cycle_EQ_128_AND_NOT_IF_ETC___d236)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_cycle.METH_write(DEF_x__h19783);
}


/* Methods */


/* Reset routines */

void MOD_mkNextFloorStop::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_testTb.reset_RST_N(ARG_rst_in);
  INST_cycle.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkNextFloorStop::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkNextFloorStop::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_cycle.dump_state(indent + 2u);
  INST_testTb.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkNextFloorStop::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 5u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_EQ_0___d2", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_EQ_128___d3", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h136", 32u);
  num = INST_cycle.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_testTb.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkNextFloorStop::dump_VCD(tVCDDumpType dt,
				   unsigned int levels,
				   MOD_mkNextFloorStop &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mkNextFloorStop::vcd_defs(tVCDDumpType dt, MOD_mkNextFloorStop &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_cycle_EQ_0___d2) != DEF_cycle_EQ_0___d2)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_EQ_0___d2, 1u);
	backing.DEF_cycle_EQ_0___d2 = DEF_cycle_EQ_0___d2;
      }
      ++num;
      if ((backing.DEF_cycle_EQ_128___d3) != DEF_cycle_EQ_128___d3)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_EQ_128___d3, 1u);
	backing.DEF_cycle_EQ_128___d3 = DEF_cycle_EQ_128___d3;
      }
      ++num;
      if ((backing.DEF_x__h136) != DEF_x__h136)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h136, 32u);
	backing.DEF_x__h136 = DEF_x__h136;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_cycle_EQ_0___d2, 1u);
      backing.DEF_cycle_EQ_0___d2 = DEF_cycle_EQ_0___d2;
      vcd_write_val(sim_hdl, num++, DEF_cycle_EQ_128___d3, 1u);
      backing.DEF_cycle_EQ_128___d3 = DEF_cycle_EQ_128___d3;
      vcd_write_val(sim_hdl, num++, DEF_x__h136, 32u);
      backing.DEF_x__h136 = DEF_x__h136;
    }
}

void MOD_mkNextFloorStop::vcd_prims(tVCDDumpType dt, MOD_mkNextFloorStop &backing)
{
  INST_cycle.dump_VCD(dt, backing.INST_cycle);
}

void MOD_mkNextFloorStop::vcd_submodules(tVCDDumpType dt,
					 unsigned int levels,
					 MOD_mkNextFloorStop &backing)
{
  INST_testTb.dump_VCD(dt, levels, backing.INST_testTb);
}
