/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Tue Mar  7 17:39:38 PST 2017
 * 
 */
#include "bluesim_primitives.h"
#include "mkNextFloorStop.h"
#include "imported_BDPI_functions.h"


/* Literal declarations */
static unsigned int const UWide_literal_96_h800000008000000080000000_arr[] = { 2147483648u,
									       2147483648u,
									       2147483648u };
static tUWide const UWide_literal_96_h800000008000000080000000(96u,
							       UWide_literal_96_h800000008000000080000000_arr);
static unsigned int const UWide_literal_96_hfffffffeffffffff00000000_arr[] = { 0u,
									       4294967295u,
									       4294967294u };
static tUWide const UWide_literal_96_hfffffffeffffffff00000000(96u,
							       UWide_literal_96_hfffffffeffffffff00000000_arr);
static unsigned int const UWide_literal_96_h0_arr[] = { 0u, 0u, 0u };
static tUWide const UWide_literal_96_h0(96u, UWide_literal_96_h0_arr);


/* String declarations */
static std::string const __str_literal_9("A PERSON AT FLOOR %d REQUEST TO GO DOWN, ONCE ENTERED CABIN HE OR SHE WILL PRESS FLOOR %d",
					 89u);
static std::string const __str_literal_8("A PERSON AT FLOOR %d REQUEST TO GO UP, ONCE ENTERED CABIN HE OR SHE WILL PRESS FLOOR %d",
					 87u);
static std::string const __str_literal_2("FAIL: ELEVATOR STALLS", 21u);
static std::string const __str_literal_4("FINISH ALL TEST", 15u);
static std::string const __str_literal_3("FINISH TEST %d", 14u);
static std::string const __str_literal_7("MOVING DIRECTION: DOWN", 22u);
static std::string const __str_literal_6("MOVING DIRECTION: UP", 20u);
static std::string const __str_literal_10("START TEST %d", 13u);
static std::string const __str_literal_1("The elevator stops at Floor %d", 30u);
static std::string const __str_literal_5("currentFloor=%d", 15u);


/* Constructor */
MOD_mkNextFloorStop::MOD_mkNextFloorStop(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_c_direction(simHdl, "c_direction", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_current(simHdl, "current", this, 32u, 0u, (tUInt8)0u),
    INST_currentFloor_ignore(simHdl, "currentFloor_ignore", this, 32u, (tUInt8)0u),
    INST_currentFloor_initialized(simHdl, "currentFloor_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_currentFloor_zaz(simHdl, "currentFloor_zaz", this, 32u, (tUInt8)0u),
    INST_cycle(simHdl, "cycle", this, 32u, 0u, (tUInt8)0u),
    INST_des(simHdl, "des", this, 3u, (tUInt8)0u, (tUInt8)0u),
    INST_direction_ignore(simHdl, "direction_ignore", this, 1u, (tUInt8)0u),
    INST_direction_initialized(simHdl, "direction_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_direction_zaz(simHdl, "direction_zaz", this, 1u, (tUInt8)0u),
    INST_display(simHdl, "display", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_down_des(simHdl, "down_des", this, 96u, UWide_literal_96_h0, (tUInt8)0u),
    INST_down_pressed(simHdl, "down_pressed", this, 3u, (tUInt8)0u, (tUInt8)0u),
    INST_floor_down_des_ignore(simHdl, "floor_down_des_ignore", this, 96u, (tUInt8)0u),
    INST_floor_down_des_initialized(simHdl,
				    "floor_down_des_initialized",
				    this,
				    1u,
				    (tUInt8)0u,
				    (tUInt8)0u),
    INST_floor_down_des_zaz(simHdl, "floor_down_des_zaz", this, 96u, (tUInt8)0u),
    INST_floor_down_pressed_ignore(simHdl, "floor_down_pressed_ignore", this, 3u, (tUInt8)0u),
    INST_floor_down_pressed_initialized(simHdl,
					"floor_down_pressed_initialized",
					this,
					1u,
					(tUInt8)0u,
					(tUInt8)0u),
    INST_floor_down_pressed_zaz(simHdl, "floor_down_pressed_zaz", this, 3u, (tUInt8)0u),
    INST_floor_up_des_ignore(simHdl, "floor_up_des_ignore", this, 96u, (tUInt8)0u),
    INST_floor_up_des_initialized(simHdl, "floor_up_des_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_floor_up_des_zaz(simHdl, "floor_up_des_zaz", this, 96u, (tUInt8)0u),
    INST_floor_up_pressed_ignore(simHdl, "floor_up_pressed_ignore", this, 3u, (tUInt8)0u),
    INST_floor_up_pressed_initialized(simHdl,
				      "floor_up_pressed_initialized",
				      this,
				      1u,
				      (tUInt8)0u,
				      (tUInt8)0u),
    INST_floor_up_pressed_zaz(simHdl, "floor_up_pressed_zaz", this, 3u, (tUInt8)0u),
    INST_nextTest(simHdl, "nextTest", this, 1u, (tUInt8)1u, (tUInt8)0u),
    INST_phase(simHdl, "phase", this, 32u, 1u, (tUInt8)0u),
    INST_reset_des_reg(simHdl, "reset_des_reg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_tle(simHdl, "tle", this, 32u, 0u, (tUInt8)0u),
    INST_up_des(simHdl, "up_des", this, 96u, UWide_literal_96_h0, (tUInt8)0u),
    INST_up_floor(simHdl, "up_floor", this, 1u, (tUInt8)1u, (tUInt8)0u),
    INST_up_pressed(simHdl, "up_pressed", this, 3u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_v__h4902(2863311530u),
    DEF_new_value__h4538(2863311530u),
    DEF_v__h3561(2863311530u),
    DEF_v__h3523(2863311530u),
    DEF_v__h3485(2863311530u),
    DEF_v__h2578(2863311530u),
    DEF_v__h1480(2863311530u),
    DEF_v__h1442(2863311530u),
    DEF_v__h1404(2863311530u),
    DEF_v__h327(2863311530u),
    DEF_x_wget__h3391(96u),
    DEF_x_wget__h1310(96u),
    DEF_down_des__h14338(96u),
    DEF_up_des__h13868(96u),
    DEF_value__h1564(96u),
    DEF_value__h3645(96u),
    DEF_new_value__h1523(96u),
    DEF_new_value__h3604(96u),
    DEF_y__h2298(96u),
    DEF_y__h4178(96u),
    DEF_v__h1561(96u),
    DEF_v__h3642(96u)
{
  symbol_count = 63u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkNextFloorStop::init_symbols_0()
{
  init_symbol(&symbols[0u], "c_direction", SYM_MODULE, &INST_c_direction);
  init_symbol(&symbols[1u], "current", SYM_MODULE, &INST_current);
  init_symbol(&symbols[2u], "currentFloor_ignore", SYM_MODULE, &INST_currentFloor_ignore);
  init_symbol(&symbols[3u], "currentFloor_initialized", SYM_MODULE, &INST_currentFloor_initialized);
  init_symbol(&symbols[4u], "currentFloor_zaz", SYM_MODULE, &INST_currentFloor_zaz);
  init_symbol(&symbols[5u], "cycle", SYM_MODULE, &INST_cycle);
  init_symbol(&symbols[6u], "des", SYM_MODULE, &INST_des);
  init_symbol(&symbols[7u], "des__h7877", SYM_DEF, &DEF_des__h7877, 3u);
  init_symbol(&symbols[8u], "des_BIT_0___h7812", SYM_DEF, &DEF_des_BIT_0___h7812, 1u);
  init_symbol(&symbols[9u], "des_BIT_1___h7845", SYM_DEF, &DEF_des_BIT_1___h7845, 1u);
  init_symbol(&symbols[10u], "des_BIT_2___h7878", SYM_DEF, &DEF_des_BIT_2___h7878, 1u);
  init_symbol(&symbols[11u], "direction_ignore", SYM_MODULE, &INST_direction_ignore);
  init_symbol(&symbols[12u], "direction_initialized", SYM_MODULE, &INST_direction_initialized);
  init_symbol(&symbols[13u], "direction_zaz", SYM_MODULE, &INST_direction_zaz);
  init_symbol(&symbols[14u], "display", SYM_MODULE, &INST_display);
  init_symbol(&symbols[15u], "display__h16295", SYM_DEF, &DEF_display__h16295, 1u);
  init_symbol(&symbols[16u], "down_des", SYM_MODULE, &INST_down_des);
  init_symbol(&symbols[17u], "down_pressed", SYM_MODULE, &INST_down_pressed);
  init_symbol(&symbols[18u], "down_pressed__h7604", SYM_DEF, &DEF_down_pressed__h7604, 3u);
  init_symbol(&symbols[19u],
	      "down_pressed_BIT_0___h7539",
	      SYM_DEF,
	      &DEF_down_pressed_BIT_0___h7539,
	      1u);
  init_symbol(&symbols[20u],
	      "down_pressed_BIT_1___h7572",
	      SYM_DEF,
	      &DEF_down_pressed_BIT_1___h7572,
	      1u);
  init_symbol(&symbols[21u],
	      "down_pressed_BIT_2___h7605",
	      SYM_DEF,
	      &DEF_down_pressed_BIT_2___h7605,
	      1u);
  init_symbol(&symbols[22u], "floor_down_des_ignore", SYM_MODULE, &INST_floor_down_des_ignore);
  init_symbol(&symbols[23u],
	      "floor_down_des_initialized",
	      SYM_MODULE,
	      &INST_floor_down_des_initialized);
  init_symbol(&symbols[24u], "floor_down_des_zaz", SYM_MODULE, &INST_floor_down_des_zaz);
  init_symbol(&symbols[25u],
	      "floor_down_pressed_ignore",
	      SYM_MODULE,
	      &INST_floor_down_pressed_ignore);
  init_symbol(&symbols[26u],
	      "floor_down_pressed_initialized",
	      SYM_MODULE,
	      &INST_floor_down_pressed_initialized);
  init_symbol(&symbols[27u], "floor_down_pressed_zaz", SYM_MODULE, &INST_floor_down_pressed_zaz);
  init_symbol(&symbols[28u], "floor_up_des_ignore", SYM_MODULE, &INST_floor_up_des_ignore);
  init_symbol(&symbols[29u], "floor_up_des_initialized", SYM_MODULE, &INST_floor_up_des_initialized);
  init_symbol(&symbols[30u], "floor_up_des_zaz", SYM_MODULE, &INST_floor_up_des_zaz);
  init_symbol(&symbols[31u], "floor_up_pressed_ignore", SYM_MODULE, &INST_floor_up_pressed_ignore);
  init_symbol(&symbols[32u],
	      "floor_up_pressed_initialized",
	      SYM_MODULE,
	      &INST_floor_up_pressed_initialized);
  init_symbol(&symbols[33u], "floor_up_pressed_zaz", SYM_MODULE, &INST_floor_up_pressed_zaz);
  init_symbol(&symbols[34u], "nextTest", SYM_MODULE, &INST_nextTest);
  init_symbol(&symbols[35u], "phase", SYM_MODULE, &INST_phase);
  init_symbol(&symbols[36u], "RL_currentFloor_every", SYM_RULE);
  init_symbol(&symbols[37u], "RL_currentFloor_every_1", SYM_RULE);
  init_symbol(&symbols[38u], "RL_direction_every", SYM_RULE);
  init_symbol(&symbols[39u], "RL_direction_every_1", SYM_RULE);
  init_symbol(&symbols[40u], "RL_finish", SYM_RULE);
  init_symbol(&symbols[41u], "RL_floor_down_des_every", SYM_RULE);
  init_symbol(&symbols[42u], "RL_floor_down_des_every_1", SYM_RULE);
  init_symbol(&symbols[43u], "RL_floor_down_pressed_every", SYM_RULE);
  init_symbol(&symbols[44u], "RL_floor_down_pressed_every_1", SYM_RULE);
  init_symbol(&symbols[45u], "RL_floor_up_des_every", SYM_RULE);
  init_symbol(&symbols[46u], "RL_floor_up_des_every_1", SYM_RULE);
  init_symbol(&symbols[47u], "RL_floor_up_pressed_every", SYM_RULE);
  init_symbol(&symbols[48u], "RL_floor_up_pressed_every_1", SYM_RULE);
  init_symbol(&symbols[49u], "RL_go_to_next_stop", SYM_RULE);
  init_symbol(&symbols[50u], "RL_reset_des", SYM_RULE);
  init_symbol(&symbols[51u], "RL_test", SYM_RULE);
  init_symbol(&symbols[52u], "RL_upFloor", SYM_RULE);
  init_symbol(&symbols[53u], "reset_des_reg", SYM_MODULE, &INST_reset_des_reg);
  init_symbol(&symbols[54u], "tle", SYM_MODULE, &INST_tle);
  init_symbol(&symbols[55u], "up_des", SYM_MODULE, &INST_up_des);
  init_symbol(&symbols[56u], "up_floor", SYM_MODULE, &INST_up_floor);
  init_symbol(&symbols[57u], "up_pressed", SYM_MODULE, &INST_up_pressed);
  init_symbol(&symbols[58u], "up_pressed__h7332", SYM_DEF, &DEF_up_pressed__h7332, 3u);
  init_symbol(&symbols[59u], "up_pressed_BIT_0___h7267", SYM_DEF, &DEF_up_pressed_BIT_0___h7267, 1u);
  init_symbol(&symbols[60u], "up_pressed_BIT_1___h7300", SYM_DEF, &DEF_up_pressed_BIT_1___h7300, 1u);
  init_symbol(&symbols[61u], "up_pressed_BIT_2___h7333", SYM_DEF, &DEF_up_pressed_BIT_2___h7333, 1u);
  init_symbol(&symbols[62u], "x__h16599", SYM_DEF, &DEF_x__h16599, 32u);
}


/* Rule actions */

void MOD_mkNextFloorStop::RL_floor_up_pressed_every()
{
  tUInt8 DEF_new_value__h369;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h327 = rand32();
  DEF_new_value__h369 = (tUInt8)((tUInt8)7u & DEF_v__h327);
  INST_floor_up_pressed_zaz.METH_wset(DEF_new_value__h369);
}

void MOD_mkNextFloorStop::RL_floor_up_pressed_every_1()
{
  DEF_x_wget__h262 = INST_floor_up_pressed_zaz.METH_wget();
  DEF_v__h408 = INST_floor_up_pressed_zaz.METH_whas() ? DEF_x_wget__h262 : (tUInt8)0u;
  INST_floor_up_pressed_ignore.METH_wset(DEF_v__h408);
}

void MOD_mkNextFloorStop::RL_floor_up_des_every()
{
  tUInt64 DEF_v_BITS_63_TO_0___h1499;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    rand32();
    DEF_v__h1404 = rand32();
  }
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h1442 = rand32();
  DEF_v_BITS_63_TO_0___h1499 = (((tUInt64)(DEF_v__h1404)) << 32u) | (tUInt64)(DEF_v__h1442);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h1480 = rand32();
  DEF_new_value__h1523.set_whole_word((tUInt32)(DEF_v_BITS_63_TO_0___h1499 >> 32u),
				      2u).build_concat((((tUInt64)((tUInt32)(DEF_v_BITS_63_TO_0___h1499))) << 32u) | (tUInt64)(DEF_v__h1480),
						       0u,
						       64u);
  INST_floor_up_des_zaz.METH_wset(DEF_new_value__h1523);
}

void MOD_mkNextFloorStop::RL_floor_up_des_every_1()
{
  DEF_x_wget__h1310 = INST_floor_up_des_zaz.METH_wget();
  DEF_value__h1564 = INST_floor_up_des_zaz.METH_whas() ? DEF_x_wget__h1310 : UWide_literal_96_h0;
  wop_rem(DEF_value__h1564, UWide_literal_96_hfffffffeffffffff00000000, DEF_y__h2298);
  wop_add(UWide_literal_96_h800000008000000080000000, DEF_y__h2298, DEF_v__h1561);
  INST_floor_up_des_ignore.METH_wset(DEF_v__h1561);
}

void MOD_mkNextFloorStop::RL_floor_down_pressed_every()
{
  tUInt8 DEF_new_value__h2620;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h2578 = rand32();
  DEF_new_value__h2620 = (tUInt8)((tUInt8)7u & DEF_v__h2578);
  INST_floor_down_pressed_zaz.METH_wset(DEF_new_value__h2620);
}

void MOD_mkNextFloorStop::RL_floor_down_pressed_every_1()
{
  DEF_x_wget__h2521 = INST_floor_down_pressed_zaz.METH_wget();
  DEF_v__h2658 = INST_floor_down_pressed_zaz.METH_whas() ? DEF_x_wget__h2521 : (tUInt8)0u;
  INST_floor_down_pressed_ignore.METH_wset(DEF_v__h2658);
}

void MOD_mkNextFloorStop::RL_floor_down_des_every()
{
  tUInt64 DEF_v_BITS_63_TO_0___h3580;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    rand32();
    DEF_v__h3485 = rand32();
  }
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h3523 = rand32();
  DEF_v_BITS_63_TO_0___h3580 = (((tUInt64)(DEF_v__h3485)) << 32u) | (tUInt64)(DEF_v__h3523);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h3561 = rand32();
  DEF_new_value__h3604.set_whole_word((tUInt32)(DEF_v_BITS_63_TO_0___h3580 >> 32u),
				      2u).build_concat((((tUInt64)((tUInt32)(DEF_v_BITS_63_TO_0___h3580))) << 32u) | (tUInt64)(DEF_v__h3561),
						       0u,
						       64u);
  INST_floor_down_des_zaz.METH_wset(DEF_new_value__h3604);
}

void MOD_mkNextFloorStop::RL_floor_down_des_every_1()
{
  DEF_x_wget__h3391 = INST_floor_down_des_zaz.METH_wget();
  DEF_value__h3645 = INST_floor_down_des_zaz.METH_whas() ? DEF_x_wget__h3391 : UWide_literal_96_h0;
  wop_rem(DEF_value__h3645, UWide_literal_96_hfffffffeffffffff00000000, DEF_y__h4178);
  wop_add(UWide_literal_96_h800000008000000080000000, DEF_y__h4178, DEF_v__h3642);
  INST_floor_down_des_ignore.METH_wset(DEF_v__h3642);
}

void MOD_mkNextFloorStop::RL_currentFloor_every()
{
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    rand32();
    DEF_new_value__h4538 = rand32();
  }
  INST_currentFloor_zaz.METH_wset(DEF_new_value__h4538);
}

void MOD_mkNextFloorStop::RL_currentFloor_every_1()
{
  DEF_x_wget__h4402 = INST_currentFloor_zaz.METH_wget();
  DEF_value__h4579 = INST_currentFloor_zaz.METH_whas() ? DEF_x_wget__h4402 : 0u;
  DEF_v__h4576 = 2147483648u + DEF_value__h4579;
  INST_currentFloor_ignore.METH_wset(DEF_v__h4576);
}

void MOD_mkNextFloorStop::RL_direction_every()
{
  tUInt8 DEF_new_value__h4944;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h4902 = rand32();
  DEF_new_value__h4944 = (tUInt8)((tUInt8)1u & DEF_v__h4902);
  INST_direction_zaz.METH_wset(DEF_new_value__h4944);
}

void MOD_mkNextFloorStop::RL_direction_every_1()
{
  DEF_direction_zaz_whas__0_AND_direction_zaz_wget__1___d52 = INST_direction_zaz.METH_whas() && INST_direction_zaz.METH_wget();
  INST_direction_ignore.METH_wset(DEF_direction_zaz_whas__0_AND_direction_zaz_wget__1___d52);
}

void MOD_mkNextFloorStop::RL_upFloor()
{
  tUInt32 DEF_IF_current_0_EQ_0_1_THEN_IF_des_8_BIT_0_9_OR_u_ETC___d93;
  tUInt32 DEF_IF_current_0_EQ_2_5_THEN_IF_des_8_BIT_2_1_OR_d_ETC___d104;
  tUInt32 DEF_IF_current_0_EQ_2_5_THEN_IF_current_0_EQ_2_5_T_ETC___d112;
  tUInt32 DEF_IF_current_0_EQ_0_1_THEN_IF_current_0_EQ_0_1_T_ETC___d108;
  tUInt32 DEF_IF_c_direction_9_THEN_IF_current_0_EQ_0_1_THEN_ETC___d113;
  tUInt8 DEF_des_8_BIT_2_1_OR_down_pressed_1_BIT_2_4___d84;
  tUInt8 DEF_des_8_BIT_1_0_OR_up_pressed_5_BIT_1_7___d83;
  tUInt8 DEF_des_8_BIT_0_9_OR_up_pressed_5_BIT_0_6___d82;
  tUInt8 DEF_des_8_BIT_1_0_OR_down_pressed_1_BIT_1_3___d96;
  tUInt8 DEF_c_direction_9_AND_NOT_current_0_SLE_IF_current_ETC___d120;
  DEF_c_direction__h18832 = INST_c_direction.METH_read();
  DEF_x__h16446 = INST_current.METH_read();
  DEF_des__h7877 = INST_des.METH_read();
  DEF_des_BIT_0___h7812 = (tUInt8)((tUInt8)1u & DEF_des__h7877);
  DEF_des_BIT_1___h7845 = (tUInt8)((tUInt8)1u & (DEF_des__h7877 >> 1u));
  DEF_des_BIT_2___h7878 = (tUInt8)(DEF_des__h7877 >> 2u);
  DEF_down_pressed__h7604 = INST_down_pressed.METH_read();
  DEF_down_pressed_BIT_2___h7605 = (tUInt8)(DEF_down_pressed__h7604 >> 2u);
  DEF_down_pressed_BIT_1___h7572 = (tUInt8)((tUInt8)1u & (DEF_down_pressed__h7604 >> 1u));
  DEF_des_8_BIT_1_0_OR_down_pressed_1_BIT_1_3___d96 = DEF_des_BIT_1___h7845 || DEF_down_pressed_BIT_1___h7572;
  DEF_des_8_BIT_2_1_OR_down_pressed_1_BIT_2_4___d84 = DEF_des_BIT_2___h7878 || DEF_down_pressed_BIT_2___h7605;
  DEF_up_pressed__h7332 = INST_up_pressed.METH_read();
  DEF_up_pressed_BIT_1___h7300 = (tUInt8)((tUInt8)1u & (DEF_up_pressed__h7332 >> 1u));
  DEF_up_pressed_BIT_0___h7267 = (tUInt8)((tUInt8)1u & DEF_up_pressed__h7332);
  DEF_des_8_BIT_0_9_OR_up_pressed_5_BIT_0_6___d82 = DEF_des_BIT_0___h7812 || DEF_up_pressed_BIT_0___h7267;
  DEF_des_8_BIT_1_0_OR_up_pressed_5_BIT_1_7___d83 = DEF_des_BIT_1___h7845 || DEF_up_pressed_BIT_1___h7300;
  switch (DEF_x__h16446) {
  case 2u:
    DEF_IF_current_0_EQ_2_5_THEN_IF_des_8_BIT_2_1_OR_d_ETC___d104 = DEF_des_8_BIT_2_1_OR_down_pressed_1_BIT_2_4___d84 ? 2u : (DEF_des_8_BIT_1_0_OR_down_pressed_1_BIT_1_3___d96 ? 1u : (DEF_des_8_BIT_0_9_OR_up_pressed_5_BIT_0_6___d82 ? 0u : (DEF_up_pressed_BIT_1___h7300 ? 1u : 2u)));
    break;
  case 1u:
    DEF_IF_current_0_EQ_2_5_THEN_IF_des_8_BIT_2_1_OR_d_ETC___d104 = DEF_des_8_BIT_1_0_OR_down_pressed_1_BIT_1_3___d96 ? 1u : (DEF_des_8_BIT_0_9_OR_up_pressed_5_BIT_0_6___d82 ? 0u : 1u);
    break;
  default:
    DEF_IF_current_0_EQ_2_5_THEN_IF_des_8_BIT_2_1_OR_d_ETC___d104 = 0u;
  }
  switch (DEF_x__h16446) {
  case 0u:
    DEF_IF_current_0_EQ_0_1_THEN_IF_des_8_BIT_0_9_OR_u_ETC___d93 = DEF_des_8_BIT_0_9_OR_up_pressed_5_BIT_0_6___d82 ? 0u : (DEF_des_8_BIT_1_0_OR_up_pressed_5_BIT_1_7___d83 ? 1u : (DEF_des_8_BIT_2_1_OR_down_pressed_1_BIT_2_4___d84 ? 2u : (DEF_down_pressed_BIT_1___h7572 ? 1u : 0u)));
    break;
  case 1u:
    DEF_IF_current_0_EQ_0_1_THEN_IF_des_8_BIT_0_9_OR_u_ETC___d93 = DEF_des_8_BIT_1_0_OR_up_pressed_5_BIT_1_7___d83 ? 1u : (DEF_des_8_BIT_2_1_OR_down_pressed_1_BIT_2_4___d84 ? 2u : 1u);
    break;
  default:
    DEF_IF_current_0_EQ_0_1_THEN_IF_des_8_BIT_0_9_OR_u_ETC___d93 = 2u;
  }
  switch (DEF_x__h16446) {
  case 0u:
    DEF_IF_current_0_EQ_0_1_THEN_IF_current_0_EQ_0_1_T_ETC___d108 = DEF_IF_current_0_EQ_0_1_THEN_IF_des_8_BIT_0_9_OR_u_ETC___d93;
    break;
  case 1u:
    DEF_IF_current_0_EQ_0_1_THEN_IF_current_0_EQ_0_1_T_ETC___d108 = DEF_up_pressed_BIT_0___h7267 || DEF_des_BIT_0___h7812 ? DEF_IF_current_0_EQ_2_5_THEN_IF_des_8_BIT_2_1_OR_d_ETC___d104 : DEF_IF_current_0_EQ_0_1_THEN_IF_des_8_BIT_0_9_OR_u_ETC___d93;
    break;
  case 2u:
    DEF_IF_current_0_EQ_0_1_THEN_IF_current_0_EQ_0_1_T_ETC___d108 = DEF_IF_current_0_EQ_2_5_THEN_IF_des_8_BIT_2_1_OR_d_ETC___d104;
    break;
  default:
    DEF_IF_current_0_EQ_0_1_THEN_IF_current_0_EQ_0_1_T_ETC___d108 = DEF_x__h16446;
  }
  switch (DEF_x__h16446) {
  case 2u:
    DEF_IF_current_0_EQ_2_5_THEN_IF_current_0_EQ_2_5_T_ETC___d112 = DEF_IF_current_0_EQ_2_5_THEN_IF_des_8_BIT_2_1_OR_d_ETC___d104;
    break;
  case 1u:
    DEF_IF_current_0_EQ_2_5_THEN_IF_current_0_EQ_2_5_T_ETC___d112 = DEF_down_pressed_BIT_2___h7605 ? DEF_IF_current_0_EQ_0_1_THEN_IF_des_8_BIT_0_9_OR_u_ETC___d93 : DEF_IF_current_0_EQ_2_5_THEN_IF_des_8_BIT_2_1_OR_d_ETC___d104;
    break;
  case 0u:
    DEF_IF_current_0_EQ_2_5_THEN_IF_current_0_EQ_2_5_T_ETC___d112 = DEF_IF_current_0_EQ_0_1_THEN_IF_des_8_BIT_0_9_OR_u_ETC___d93;
    break;
  default:
    DEF_IF_current_0_EQ_2_5_THEN_IF_current_0_EQ_2_5_T_ETC___d112 = DEF_x__h16446;
  }
  DEF_IF_c_direction_9_THEN_IF_current_0_EQ_0_1_THEN_ETC___d113 = DEF_c_direction__h18832 ? DEF_IF_current_0_EQ_0_1_THEN_IF_current_0_EQ_0_1_T_ETC___d108 : DEF_IF_current_0_EQ_2_5_THEN_IF_current_0_EQ_2_5_T_ETC___d112;
  DEF_NOT_c_direction_9___d117 = !DEF_c_direction__h18832;
  DEF_c_direction_9_AND_NOT_current_0_SLE_IF_current_ETC___d120 = (DEF_c_direction__h18832 && !primSLE8(1u,
													32u,
													(tUInt32)(DEF_x__h16446),
													32u,
													(tUInt32)(DEF_IF_current_0_EQ_0_1_THEN_IF_current_0_EQ_0_1_T_ETC___d108))) || (DEF_NOT_c_direction_9___d117 && primSLT8(1u,
																												32u,
																												(tUInt32)(DEF_x__h16446),
																												32u,
																												(tUInt32)(DEF_IF_current_0_EQ_2_5_THEN_IF_current_0_EQ_2_5_T_ETC___d112)));
  INST_phase.METH_write(1u);
  INST_up_floor.METH_write((tUInt8)0u);
  INST_current.METH_write(DEF_IF_c_direction_9_THEN_IF_current_0_EQ_0_1_THEN_ETC___d113);
  if (DEF_c_direction_9_AND_NOT_current_0_SLE_IF_current_ETC___d120)
    INST_c_direction.METH_write(DEF_NOT_c_direction_9___d117);
}

void MOD_mkNextFloorStop::RL_go_to_next_stop()
{
  tUInt32 DEF_tle_23_PLUS_1___d124;
  tUInt8 DEF_NOT_tle_23_SLE_20_26___d127;
  tUInt8 DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d143;
  tUInt8 DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d152;
  tUInt8 DEF_NOT_c_direction_9_17_AND_NOT_SEL_ARR_down_pres_ETC___d196;
  tUInt8 DEF_c_direction_9_AND_NOT_SEL_ARR_up_pressed_5_BIT_ETC___d207;
  tUInt8 DEF_NOT_current_0_EQ_2_5_98_AND_up_pressed_5_BIT_2_ETC___d204;
  tUInt8 DEF_NOT_current_0_EQ_2_5_98_AND_down_pressed_1_BIT_ETC___d213;
  tUInt8 DEF_IF_c_direction_9_THEN_IF_SEL_ARR_up_pressed_5__ETC___d192;
  tUInt8 DEF_SEL_ARR_1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN__ETC___d178;
  tUInt8 DEF_SEL_ARR_down_des_79_BITS_31_TO_0_80_0_1_81_cur_ETC___d189;
  tUInt32 DEF_b__h11869;
  tUInt32 DEF_signed_current_0___d125;
  tUInt32 DEF_x__h15352;
  tUInt32 DEF_x__h14890;
  tUInt8 DEF_c_direction_9_AND_SEL_ARR_up_pressed_5_BIT_0_6_ETC___d155;
  tUInt8 DEF_c_direction_9_AND_SEL_ARR_up_pressed_5_BIT_0_6_ETC___d197;
  tUInt8 DEF_c_direction_9_AND_NOT_SEL_ARR_up_pressed_5_BIT_ETC___d209;
  tUInt8 DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d134;
  tUInt8 DEF_c_direction_9_AND_NOT_SEL_ARR_up_pressed_5_BIT_ETC___d214;
  tUInt8 DEF_SEL_ARR_NOT_down_pressed_1_BIT_0_2_46_NOT_down_ETC___d150;
  tUInt8 DEF_SEL_ARR_up_pressed_5_BIT_0_6_up_pressed_5_BIT__ETC___d129;
  tUInt8 DEF_SEL_ARR_NOT_up_pressed_5_BIT_0_6_35_NOT_up_pre_ETC___d139;
  tUInt8 DEF_SEL_ARR_down_pressed_1_BIT_0_2_down_pressed_1__ETC___d142;
  DEF_c_direction__h18832 = INST_c_direction.METH_read();
  DEF_x__h16446 = INST_current.METH_read();
  DEF_signed_current_0___d125 = DEF_x__h16446;
  DEF_down_des__h14338 = INST_down_des.METH_read();
  DEF_v__h14224 = DEF_down_des__h14338.get_whole_word(0u);
  switch (DEF_x__h16446) {
  case 0u:
    DEF_x__h14890 = DEF_v__h14224;
    break;
  case 1u:
    DEF_x__h14890 = 0u;
    break;
  case 2u:
    DEF_x__h14890 = 1u;
    break;
  default:
    DEF_x__h14890 = 2863311530u;
  }
  DEF_up_des__h13868 = INST_up_des.METH_read();
  DEF_v__h13653 = DEF_up_des__h13868.get_whole_word(2u);
  DEF_b__h11869 = INST_tle.METH_read();
  DEF_des__h7877 = INST_des.METH_read();
  DEF_des_BIT_0___h7812 = (tUInt8)((tUInt8)1u & DEF_des__h7877);
  DEF_des_BIT_1___h7845 = (tUInt8)((tUInt8)1u & (DEF_des__h7877 >> 1u));
  DEF_des_BIT_2___h7878 = (tUInt8)(DEF_des__h7877 >> 2u);
  DEF_down_pressed__h7604 = INST_down_pressed.METH_read();
  DEF_down_pressed_BIT_2___h7605 = (tUInt8)(DEF_down_pressed__h7604 >> 2u);
  DEF_down_pressed_BIT_1___h7572 = (tUInt8)((tUInt8)1u & (DEF_down_pressed__h7604 >> 1u));
  DEF_down_pressed_BIT_0___h7539 = (tUInt8)((tUInt8)1u & DEF_down_pressed__h7604);
  switch (DEF_x__h16446) {
  case 0u:
    DEF_SEL_ARR_down_pressed_1_BIT_0_2_down_pressed_1__ETC___d142 = DEF_down_pressed_BIT_0___h7539;
    break;
  case 1u:
    DEF_SEL_ARR_down_pressed_1_BIT_0_2_down_pressed_1__ETC___d142 = DEF_down_pressed_BIT_1___h7572;
    break;
  case 2u:
    DEF_SEL_ARR_down_pressed_1_BIT_0_2_down_pressed_1__ETC___d142 = DEF_down_pressed_BIT_2___h7605;
    break;
  default:
    DEF_SEL_ARR_down_pressed_1_BIT_0_2_down_pressed_1__ETC___d142 = (tUInt8)0u;
  }
  DEF_up_pressed__h7332 = INST_up_pressed.METH_read();
  DEF_up_pressed_BIT_1___h7300 = (tUInt8)((tUInt8)1u & (DEF_up_pressed__h7332 >> 1u));
  DEF_up_pressed_BIT_0___h7267 = (tUInt8)((tUInt8)1u & DEF_up_pressed__h7332);
  DEF_up_pressed_BIT_2___h7333 = (tUInt8)(DEF_up_pressed__h7332 >> 2u);
  switch (DEF_x__h16446) {
  case 0u:
    DEF_SEL_ARR_up_pressed_5_BIT_0_6_up_pressed_5_BIT__ETC___d129 = DEF_up_pressed_BIT_0___h7267;
    break;
  case 1u:
    DEF_SEL_ARR_up_pressed_5_BIT_0_6_up_pressed_5_BIT__ETC___d129 = DEF_up_pressed_BIT_1___h7300;
    break;
  case 2u:
    DEF_SEL_ARR_up_pressed_5_BIT_0_6_up_pressed_5_BIT__ETC___d129 = DEF_up_pressed_BIT_2___h7333;
    break;
  default:
    DEF_SEL_ARR_up_pressed_5_BIT_0_6_up_pressed_5_BIT__ETC___d129 = (tUInt8)0u;
  }
  DEF_x__h13816 = DEF_up_des__h13868.get_whole_word(0u);
  DEF_up_des_BIT_31___h13787 = DEF_up_des__h13868.get_bits_in_word8(0u, 31u, 1u);
  DEF_NOT_down_pressed_1_BIT_0_2___d146 = !DEF_down_pressed_BIT_0___h7539;
  DEF_NOT_down_pressed_1_BIT_1_3___d147 = !DEF_down_pressed_BIT_1___h7572;
  DEF_NOT_down_pressed_1_BIT_2_4___d148 = !DEF_down_pressed_BIT_2___h7605;
  switch (DEF_x__h16446) {
  case 0u:
    DEF_SEL_ARR_NOT_down_pressed_1_BIT_0_2_46_NOT_down_ETC___d150 = DEF_NOT_down_pressed_1_BIT_0_2___d146;
    break;
  case 1u:
    DEF_SEL_ARR_NOT_down_pressed_1_BIT_0_2_46_NOT_down_ETC___d150 = DEF_NOT_down_pressed_1_BIT_1_3___d147;
    break;
  case 2u:
    DEF_SEL_ARR_NOT_down_pressed_1_BIT_0_2_46_NOT_down_ETC___d150 = DEF_NOT_down_pressed_1_BIT_2_4___d148;
    break;
  default:
    DEF_SEL_ARR_NOT_down_pressed_1_BIT_0_2_46_NOT_down_ETC___d150 = (tUInt8)0u;
  }
  DEF_NOT_up_pressed_5_BIT_0_6___d135 = !DEF_up_pressed_BIT_0___h7267;
  DEF_NOT_up_pressed_5_BIT_1_7___d136 = !DEF_up_pressed_BIT_1___h7300;
  DEF_NOT_up_pressed_5_BIT_2_8___d137 = !DEF_up_pressed_BIT_2___h7333;
  switch (DEF_x__h16446) {
  case 0u:
    DEF_SEL_ARR_NOT_up_pressed_5_BIT_0_6_35_NOT_up_pre_ETC___d139 = DEF_NOT_up_pressed_5_BIT_0_6___d135;
    break;
  case 1u:
    DEF_SEL_ARR_NOT_up_pressed_5_BIT_0_6_35_NOT_up_pre_ETC___d139 = DEF_NOT_up_pressed_5_BIT_1_7___d136;
    break;
  case 2u:
    DEF_SEL_ARR_NOT_up_pressed_5_BIT_0_6_35_NOT_up_pre_ETC___d139 = DEF_NOT_up_pressed_5_BIT_2_8___d137;
    break;
  default:
    DEF_SEL_ARR_NOT_up_pressed_5_BIT_0_6_35_NOT_up_pre_ETC___d139 = (tUInt8)0u;
  }
  DEF_NOT_des_8_BIT_0_9___d130 = !DEF_des_BIT_0___h7812;
  DEF_NOT_des_8_BIT_1_0___d131 = !DEF_des_BIT_1___h7845;
  DEF_NOT_des_8_BIT_2_1___d132 = !DEF_des_BIT_2___h7878;
  switch (DEF_x__h16446) {
  case 0u:
    DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d134 = DEF_NOT_des_8_BIT_0_9___d130;
    break;
  case 1u:
    DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d134 = DEF_NOT_des_8_BIT_1_0___d131;
    break;
  case 2u:
    DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d134 = DEF_NOT_des_8_BIT_2_1___d132;
    break;
  default:
    DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d134 = (tUInt8)0u;
  }
  DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162 = (tUInt32)((tUInt8)((tUInt8)1u & (DEF_up_des_BIT_31___h13787 ? -DEF_x__h13816 : DEF_x__h13816)));
  DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164 = DEF_up_des_BIT_31___h13787 ? -DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162 : DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162;
  DEF__1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CO_ETC___d168 = 1u + ((tUInt8)(DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164 >> 31u) ? -DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164 : DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164);
  switch (DEF_x__h16446) {
  case 0u:
    DEF_x__h15352 = DEF__1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CO_ETC___d168;
    break;
  case 1u:
    DEF_x__h15352 = 2u;
    break;
  case 2u:
    DEF_x__h15352 = DEF_v__h13653;
    break;
  default:
    DEF_x__h15352 = 2863311530u;
  }
  DEF_SEL_ARR_down_des_79_BITS_31_TO_0_80_0_1_81_cur_ETC___d189 = (tUInt8)7u & ((((DEF_x__h14890 == 2u || DEF_des_BIT_2___h7878) << 2u) | ((DEF_x__h14890 == 1u || DEF_des_BIT_1___h7845) << 1u)) | (DEF_x__h14890 == 0u || DEF_des_BIT_0___h7812));
  DEF_SEL_ARR_1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN__ETC___d178 = (tUInt8)7u & ((((DEF_x__h15352 == 2u || DEF_des_BIT_2___h7878) << 2u) | ((DEF_x__h15352 == 1u || DEF_des_BIT_1___h7845) << 1u)) | (DEF_x__h15352 == 0u || DEF_des_BIT_0___h7812));
  DEF_IF_c_direction_9_THEN_IF_SEL_ARR_up_pressed_5__ETC___d192 = DEF_c_direction__h18832 ? (DEF_SEL_ARR_up_pressed_5_BIT_0_6_up_pressed_5_BIT__ETC___d129 ? DEF_SEL_ARR_1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN__ETC___d178 : DEF_SEL_ARR_down_des_79_BITS_31_TO_0_80_0_1_81_cur_ETC___d189) : (DEF_SEL_ARR_down_pressed_1_BIT_0_2_down_pressed_1__ETC___d142 ? DEF_SEL_ARR_down_des_79_BITS_31_TO_0_80_0_1_81_cur_ETC___d189 : DEF_SEL_ARR_1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN__ETC___d178);
  DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d152 = (DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d134 && DEF_SEL_ARR_NOT_down_pressed_1_BIT_0_2_46_NOT_down_ETC___d150) && DEF_SEL_ARR_up_pressed_5_BIT_0_6_up_pressed_5_BIT__ETC___d129;
  DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d143 = (DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d134 && DEF_SEL_ARR_NOT_up_pressed_5_BIT_0_6_35_NOT_up_pre_ETC___d139) && DEF_SEL_ARR_down_pressed_1_BIT_0_2_down_pressed_1__ETC___d142;
  DEF_c_direction_9_AND_NOT_SEL_ARR_up_pressed_5_BIT_ETC___d207 = DEF_c_direction__h18832 && (!DEF_SEL_ARR_up_pressed_5_BIT_0_6_up_pressed_5_BIT__ETC___d129 && DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d143);
  DEF_NOT_c_direction_9___d117 = !DEF_c_direction__h18832;
  DEF_c_direction_9_AND_NOT_SEL_ARR_up_pressed_5_BIT_ETC___d209 = DEF_c_direction_9_AND_NOT_SEL_ARR_up_pressed_5_BIT_ETC___d207 || (DEF_NOT_c_direction_9___d117 && DEF_SEL_ARR_down_pressed_1_BIT_0_2_down_pressed_1__ETC___d142);
  DEF_c_direction_9_AND_SEL_ARR_up_pressed_5_BIT_0_6_ETC___d155 = (DEF_c_direction__h18832 && (DEF_SEL_ARR_up_pressed_5_BIT_0_6_up_pressed_5_BIT__ETC___d129 || DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d143)) || (DEF_NOT_c_direction_9___d117 && (DEF_SEL_ARR_down_pressed_1_BIT_0_2_down_pressed_1__ETC___d142 || DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d152));
  DEF_NOT_c_direction_9_17_AND_NOT_SEL_ARR_down_pres_ETC___d196 = DEF_NOT_c_direction_9___d117 && (!DEF_SEL_ARR_down_pressed_1_BIT_0_2_down_pressed_1__ETC___d142 && DEF_SEL_ARR_NOT_des_8_BIT_0_9_30_NOT_des_8_BIT_1_0_ETC___d152);
  DEF_c_direction_9_AND_NOT_SEL_ARR_up_pressed_5_BIT_ETC___d214 = DEF_c_direction_9_AND_NOT_SEL_ARR_up_pressed_5_BIT_ETC___d207 || DEF_NOT_c_direction_9_17_AND_NOT_SEL_ARR_down_pres_ETC___d196;
  DEF_c_direction_9_AND_SEL_ARR_up_pressed_5_BIT_0_6_ETC___d197 = (DEF_c_direction__h18832 && DEF_SEL_ARR_up_pressed_5_BIT_0_6_up_pressed_5_BIT__ETC___d129) || DEF_NOT_c_direction_9_17_AND_NOT_SEL_ARR_down_pres_ETC___d196;
  DEF_NOT_current_0_EQ_0_1___d202 = !(DEF_x__h16446 == 0u);
  DEF_NOT_current_0_EQ_2_5___d198 = !(DEF_x__h16446 == 2u);
  DEF_NOT_current_0_EQ_1_9___d200 = !(DEF_x__h16446 == 1u);
  DEF_NOT_current_0_EQ_2_5_98_AND_down_pressed_1_BIT_ETC___d213 = (tUInt8)7u & ((((DEF_NOT_current_0_EQ_2_5___d198 && DEF_down_pressed_BIT_2___h7605) << 2u) | ((DEF_NOT_current_0_EQ_1_9___d200 && DEF_down_pressed_BIT_1___h7572) << 1u)) | (DEF_NOT_current_0_EQ_0_1___d202 && DEF_down_pressed_BIT_0___h7539));
  DEF_NOT_current_0_EQ_2_5_98_AND_up_pressed_5_BIT_2_ETC___d204 = (tUInt8)7u & ((((DEF_NOT_current_0_EQ_2_5___d198 && DEF_up_pressed_BIT_2___h7333) << 2u) | ((DEF_NOT_current_0_EQ_1_9___d200 && DEF_up_pressed_BIT_1___h7300) << 1u)) | (DEF_NOT_current_0_EQ_0_1___d202 && DEF_up_pressed_BIT_0___h7267));
  DEF_NOT_tle_23_SLE_20_26___d127 = !primSLE8(1u, 32u, (tUInt32)(DEF_b__h11869), 32u, 20u);
  DEF_tle_23_PLUS_1___d124 = DEF_b__h11869 + 1u;
  INST_phase.METH_write(2u);
  INST_up_floor.METH_write((tUInt8)1u);
  INST_reset_des_reg.METH_write((tUInt8)1u);
  INST_tle.METH_write(DEF_tle_23_PLUS_1___d124);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl, this, "s,-32", &__str_literal_1, DEF_signed_current_0___d125);
    if (DEF_NOT_tle_23_SLE_20_26___d127)
      dollar_display(sim_hdl, this, "s", &__str_literal_2);
    if (DEF_NOT_tle_23_SLE_20_26___d127)
      dollar_finish(sim_hdl, "32", 0u);
  }
  if (DEF_c_direction_9_AND_SEL_ARR_up_pressed_5_BIT_0_6_ETC___d155)
    INST_des.METH_write(DEF_IF_c_direction_9_THEN_IF_SEL_ARR_up_pressed_5__ETC___d192);
  if (DEF_c_direction_9_AND_SEL_ARR_up_pressed_5_BIT_0_6_ETC___d197)
    INST_up_pressed.METH_write(DEF_NOT_current_0_EQ_2_5_98_AND_up_pressed_5_BIT_2_ETC___d204);
  if (DEF_c_direction_9_AND_NOT_SEL_ARR_up_pressed_5_BIT_ETC___d209)
    INST_down_pressed.METH_write(DEF_NOT_current_0_EQ_2_5_98_AND_down_pressed_1_BIT_ETC___d213);
  if (DEF_c_direction_9_AND_NOT_SEL_ARR_up_pressed_5_BIT_ETC___d214)
    INST_c_direction.METH_write(DEF_NOT_c_direction_9___d117);
}

void MOD_mkNextFloorStop::RL_finish()
{
  DEF_x__h16599 = INST_cycle.METH_read();
  DEF_x__h16595 = DEF_x__h16599 + 1u;
  INST_cycle.METH_write(DEF_x__h16595);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,32", &__str_literal_3, DEF_x__h16599);
  INST_nextTest.METH_write((tUInt8)1u);
}

void MOD_mkNextFloorStop::RL_reset_des()
{
  tUInt8 DEF_NOT_current_0_EQ_2_5_98_AND_des_8_BIT_2_1_30_C_ETC___d233;
  tUInt8 DEF_SEL_ARR_des_8_BIT_0_9_des_8_BIT_1_0_des_8_BIT__ETC___d229;
  DEF_x__h16446 = INST_current.METH_read();
  DEF_des__h7877 = INST_des.METH_read();
  DEF_des_BIT_0___h7812 = (tUInt8)((tUInt8)1u & DEF_des__h7877);
  DEF_des_BIT_1___h7845 = (tUInt8)((tUInt8)1u & (DEF_des__h7877 >> 1u));
  DEF_des_BIT_2___h7878 = (tUInt8)(DEF_des__h7877 >> 2u);
  switch (DEF_x__h16446) {
  case 0u:
    DEF_SEL_ARR_des_8_BIT_0_9_des_8_BIT_1_0_des_8_BIT__ETC___d229 = DEF_des_BIT_0___h7812;
    break;
  case 1u:
    DEF_SEL_ARR_des_8_BIT_0_9_des_8_BIT_1_0_des_8_BIT__ETC___d229 = DEF_des_BIT_1___h7845;
    break;
  case 2u:
    DEF_SEL_ARR_des_8_BIT_0_9_des_8_BIT_1_0_des_8_BIT__ETC___d229 = DEF_des_BIT_2___h7878;
    break;
  default:
    DEF_SEL_ARR_des_8_BIT_0_9_des_8_BIT_1_0_des_8_BIT__ETC___d229 = (tUInt8)0u;
  }
  DEF_NOT_current_0_EQ_0_1___d202 = !(DEF_x__h16446 == 0u);
  DEF_NOT_current_0_EQ_1_9___d200 = !(DEF_x__h16446 == 1u);
  DEF_NOT_current_0_EQ_2_5___d198 = !(DEF_x__h16446 == 2u);
  DEF_NOT_current_0_EQ_2_5_98_AND_des_8_BIT_2_1_30_C_ETC___d233 = (tUInt8)7u & ((((DEF_NOT_current_0_EQ_2_5___d198 && DEF_des_BIT_2___h7878) << 2u) | ((DEF_NOT_current_0_EQ_1_9___d200 && DEF_des_BIT_1___h7845) << 1u)) | (DEF_NOT_current_0_EQ_0_1___d202 && DEF_des_BIT_0___h7812));
  INST_phase.METH_write(0u);
  if (DEF_SEL_ARR_des_8_BIT_0_9_des_8_BIT_1_0_des_8_BIT__ETC___d229)
    INST_reset_des_reg.METH_write((tUInt8)0u);
  if (DEF_SEL_ARR_des_8_BIT_0_9_des_8_BIT_1_0_des_8_BIT__ETC___d229)
    INST_des.METH_write(DEF_NOT_current_0_EQ_2_5_98_AND_des_8_BIT_2_1_30_C_ETC___d233);
}

void MOD_mkNextFloorStop::RL_test()
{
  tUInt8 DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d248;
  tUInt8 DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d251;
  tUInt8 DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d264;
  tUInt8 DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d267;
  tUInt8 DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d270;
  tUInt8 DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d275;
  tUInt8 DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d279;
  tUInt8 DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d284;
  tUInt8 DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d287;
  tUInt8 DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d291;
  tUInt8 DEF_NOT_cycle_24_EQ_0_34___d246;
  tUInt8 DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d293;
  tUInt8 DEF_NOT_display_36___d249;
  tUInt8 DEF_NOT_cycle_24_EQ_128_35___d247;
  tUInt8 DEF_IF_floor_down_pressed_zaz_whas__4_THEN_floor_d_ETC___d306;
  tUInt8 DEF__0_CONCAT_IF_floor_up_pressed_zaz_whas_THEN_flo_ETC___d304;
  tUInt32 DEF_x__h16428;
  tUInt32 DEF_IF_current_0_BIT_31_52_THEN_NEG_current_0_53_E_ETC___d255;
  tUInt32 DEF_x__h16925;
  tUInt32 DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__2_ETC___d297;
  tUInt32 DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d302;
  tUInt8 DEF_current_BIT_31___h16442;
  tUInt32 DEF_IF_current_0_BIT_31_52_THEN_NEG_IF_current_0_B_ETC___d257;
  tUInt8 DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__2_TH_ETC___d294;
  tUInt32 DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__2_ETC___d299;
  tUInt32 DEF_signed_1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN__ETC___d272;
  tUInt32 DEF_signed_up_des_56_BITS_95_TO_64_69___d288;
  tUInt32 DEF_signed_down_des_79_BITS_31_TO_0_80___d276;
  tUInt32 DEF_signed_IF_IF_current_0_BIT_31_52_THEN_NEG_IF__ETC___d261;
  tUInt32 DEF_signed_0___d271;
  tUInt32 DEF_signed_1___d280;
  tUInt32 DEF_signed_2___d281;
  DEF_c_direction__h18832 = INST_c_direction.METH_read();
  DEF_x__h16446 = INST_current.METH_read();
  DEF_signed_2___d281 = 2u;
  DEF_signed_1___d280 = 1u;
  DEF_signed_0___d271 = 0u;
  DEF_x_wget__h3391 = INST_floor_down_des_zaz.METH_wget();
  DEF_x_wget__h1310 = INST_floor_up_des_zaz.METH_wget();
  DEF_down_des__h14338 = INST_down_des.METH_read();
  DEF_v__h14224 = DEF_down_des__h14338.get_whole_word(0u);
  DEF_signed_down_des_79_BITS_31_TO_0_80___d276 = DEF_v__h14224;
  DEF_up_des__h13868 = INST_up_des.METH_read();
  DEF_v__h13653 = DEF_up_des__h13868.get_whole_word(2u);
  DEF_signed_up_des_56_BITS_95_TO_64_69___d288 = DEF_v__h13653;
  DEF_x_wget__h4402 = INST_currentFloor_zaz.METH_wget();
  DEF_x_wget__h262 = INST_floor_up_pressed_zaz.METH_wget();
  DEF_x__h16599 = INST_cycle.METH_read();
  DEF_x_wget__h2521 = INST_floor_down_pressed_zaz.METH_wget();
  DEF_down_pressed__h7604 = INST_down_pressed.METH_read();
  DEF_down_pressed_BIT_2___h7605 = (tUInt8)(DEF_down_pressed__h7604 >> 2u);
  DEF_down_pressed_BIT_1___h7572 = (tUInt8)((tUInt8)1u & (DEF_down_pressed__h7604 >> 1u));
  DEF_down_pressed_BIT_0___h7539 = (tUInt8)((tUInt8)1u & DEF_down_pressed__h7604);
  DEF_up_pressed__h7332 = INST_up_pressed.METH_read();
  DEF_up_pressed_BIT_1___h7300 = (tUInt8)((tUInt8)1u & (DEF_up_pressed__h7332 >> 1u));
  DEF_up_pressed_BIT_0___h7267 = (tUInt8)((tUInt8)1u & DEF_up_pressed__h7332);
  DEF_up_pressed_BIT_2___h7333 = (tUInt8)(DEF_up_pressed__h7332 >> 2u);
  DEF_display__h16295 = INST_display.METH_read();
  DEF_x__h13816 = DEF_up_des__h13868.get_whole_word(0u);
  DEF_v__h2658 = INST_floor_down_pressed_zaz.METH_whas() ? DEF_x_wget__h2521 : (tUInt8)0u;
  DEF_up_des_BIT_31___h13787 = DEF_up_des__h13868.get_bits_in_word8(0u, 31u, 1u);
  DEF_v__h408 = INST_floor_up_pressed_zaz.METH_whas() ? DEF_x_wget__h262 : (tUInt8)0u;
  DEF_current_BIT_31___h16442 = (tUInt8)(DEF_x__h16446 >> 31u);
  DEF_value__h1564 = INST_floor_up_des_zaz.METH_whas() ? DEF_x_wget__h1310 : UWide_literal_96_h0;
  DEF_value__h3645 = INST_floor_down_des_zaz.METH_whas() ? DEF_x_wget__h3391 : UWide_literal_96_h0;
  DEF_x__h16428 = DEF_current_BIT_31___h16442 ? -DEF_x__h16446 : DEF_x__h16446;
  DEF_IF_current_0_BIT_31_52_THEN_NEG_current_0_53_E_ETC___d255 = DEF_x__h16428 % 3u;
  DEF_IF_current_0_BIT_31_52_THEN_NEG_IF_current_0_B_ETC___d257 = DEF_current_BIT_31___h16442 ? -DEF_IF_current_0_BIT_31_52_THEN_NEG_current_0_53_E_ETC___d255 : DEF_IF_current_0_BIT_31_52_THEN_NEG_current_0_53_E_ETC___d255;
  DEF_signed_IF_IF_current_0_BIT_31_52_THEN_NEG_IF__ETC___d261 = (tUInt8)(DEF_IF_current_0_BIT_31_52_THEN_NEG_IF_current_0_B_ETC___d257 >> 31u) ? -DEF_IF_current_0_BIT_31_52_THEN_NEG_IF_current_0_B_ETC___d257 : DEF_IF_current_0_BIT_31_52_THEN_NEG_IF_current_0_B_ETC___d257;
  DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162 = (tUInt32)((tUInt8)((tUInt8)1u & (DEF_up_des_BIT_31___h13787 ? -DEF_x__h13816 : DEF_x__h13816)));
  DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164 = DEF_up_des_BIT_31___h13787 ? -DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162 : DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162;
  DEF__1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CO_ETC___d168 = 1u + ((tUInt8)(DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164 >> 31u) ? -DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164 : DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164);
  DEF_signed_1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN__ETC___d272 = DEF__1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CO_ETC___d168;
  DEF_value__h4579 = INST_currentFloor_zaz.METH_whas() ? DEF_x_wget__h4402 : 0u;
  DEF_v__h4576 = 2147483648u + DEF_value__h4579;
  DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__2_TH_ETC___d294 = (tUInt8)(DEF_v__h4576 >> 31u);
  DEF_x__h16925 = DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__2_TH_ETC___d294 ? -DEF_v__h4576 : DEF_v__h4576;
  DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__2_ETC___d297 = DEF_x__h16925 % 3u;
  DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__2_ETC___d299 = DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__2_TH_ETC___d294 ? -DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__2_ETC___d297 : DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__2_ETC___d297;
  DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d302 = (tUInt8)(DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__2_ETC___d299 >> 31u) ? -DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__2_ETC___d299 : DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__2_ETC___d299;
  DEF_cycle_24_EQ_128___d235 = DEF_x__h16599 == 128u;
  DEF_cycle_24_EQ_0___d234 = DEF_x__h16599 == 0u;
  DEF__0_CONCAT_IF_floor_up_pressed_zaz_whas_THEN_flo_ETC___d304 = (tUInt8)7u & ((tUInt8)((tUInt8)3u & DEF_v__h408));
  DEF_IF_floor_down_pressed_zaz_whas__4_THEN_floor_d_ETC___d306 = (tUInt8)7u & (((tUInt8)(DEF_v__h2658 >> 1u)) << 1u);
  DEF_NOT_cycle_24_EQ_128_35___d247 = !DEF_cycle_24_EQ_128___d235;
  DEF_NOT_display_36___d249 = !DEF_display__h16295;
  DEF_NOT_cycle_24_EQ_0_34___d246 = !DEF_cycle_24_EQ_0___d234;
  DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d293 = DEF_NOT_cycle_24_EQ_0_34___d246 && (DEF_NOT_cycle_24_EQ_128_35___d247 && DEF_NOT_display_36___d249);
  DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d291 = DEF_NOT_cycle_24_EQ_0_34___d246 && (DEF_NOT_cycle_24_EQ_128_35___d247 && (DEF_display__h16295 && DEF_down_pressed_BIT_2___h7605));
  DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d287 = DEF_NOT_cycle_24_EQ_0_34___d246 && (DEF_NOT_cycle_24_EQ_128_35___d247 && (DEF_display__h16295 && DEF_up_pressed_BIT_2___h7333));
  DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d284 = DEF_NOT_cycle_24_EQ_0_34___d246 && (DEF_NOT_cycle_24_EQ_128_35___d247 && (DEF_display__h16295 && DEF_down_pressed_BIT_1___h7572));
  DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d279 = DEF_NOT_cycle_24_EQ_0_34___d246 && (DEF_NOT_cycle_24_EQ_128_35___d247 && (DEF_display__h16295 && DEF_up_pressed_BIT_1___h7300));
  DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d275 = DEF_NOT_cycle_24_EQ_0_34___d246 && (DEF_NOT_cycle_24_EQ_128_35___d247 && (DEF_display__h16295 && DEF_down_pressed_BIT_0___h7539));
  DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d270 = DEF_NOT_cycle_24_EQ_0_34___d246 && (DEF_NOT_cycle_24_EQ_128_35___d247 && (DEF_display__h16295 && DEF_up_pressed_BIT_0___h7267));
  DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d264 = DEF_NOT_cycle_24_EQ_0_34___d246 && (DEF_NOT_cycle_24_EQ_128_35___d247 && (DEF_display__h16295 && DEF_c_direction__h18832));
  DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d251 = DEF_NOT_cycle_24_EQ_0_34___d246 && (DEF_NOT_cycle_24_EQ_128_35___d247 && DEF_display__h16295);
  DEF_NOT_c_direction_9___d117 = !DEF_c_direction__h18832;
  DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d267 = DEF_NOT_cycle_24_EQ_0_34___d246 && (DEF_NOT_cycle_24_EQ_128_35___d247 && (DEF_display__h16295 && DEF_NOT_c_direction_9___d117));
  DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d248 = DEF_NOT_cycle_24_EQ_0_34___d246 && DEF_NOT_cycle_24_EQ_128_35___d247;
  DEF_direction_zaz_whas__0_AND_direction_zaz_wget__1___d52 = INST_direction_zaz.METH_whas() && INST_direction_zaz.METH_wget();
  wop_rem(DEF_value__h3645, UWide_literal_96_hfffffffeffffffff00000000, DEF_y__h4178);
  wop_rem(DEF_value__h1564, UWide_literal_96_hfffffffeffffffff00000000, DEF_y__h2298);
  wop_add(UWide_literal_96_h800000008000000080000000, DEF_y__h2298, DEF_v__h1561);
  wop_add(UWide_literal_96_h800000008000000080000000, DEF_y__h4178, DEF_v__h3642);
  DEF_x__h16595 = DEF_x__h16599 + 1u;
  if (DEF_cycle_24_EQ_0___d234)
    INST_floor_up_pressed_initialized.METH_write((tUInt8)1u);
  if (DEF_cycle_24_EQ_0___d234)
    INST_floor_down_pressed_initialized.METH_write((tUInt8)1u);
  if (DEF_cycle_24_EQ_0___d234)
    INST_floor_up_des_initialized.METH_write((tUInt8)1u);
  if (DEF_cycle_24_EQ_0___d234)
    INST_floor_down_des_initialized.METH_write((tUInt8)1u);
  if (DEF_cycle_24_EQ_0___d234)
    INST_currentFloor_initialized.METH_write((tUInt8)1u);
  if (DEF_cycle_24_EQ_0___d234)
    INST_direction_initialized.METH_write((tUInt8)1u);
  if (DEF_cycle_24_EQ_0___d234)
    INST_cycle.METH_write(DEF_x__h16595);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_cycle_24_EQ_128___d235)
      dollar_display(sim_hdl, this, "s", &__str_literal_4);
    if (DEF_cycle_24_EQ_128___d235)
      dollar_finish(sim_hdl, "32", 1u);
  }
  if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d248)
    INST_display.METH_write(DEF_NOT_display_36___d249);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d251)
      dollar_display(sim_hdl,
		     this,
		     "s,-32",
		     &__str_literal_5,
		     DEF_signed_IF_IF_current_0_BIT_31_52_THEN_NEG_IF__ETC___d261);
    if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d264)
      dollar_display(sim_hdl, this, "s", &__str_literal_6);
    if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d267)
      dollar_display(sim_hdl, this, "s", &__str_literal_7);
    if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d270)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32",
		     &__str_literal_8,
		     DEF_signed_0___d271,
		     DEF_signed_1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN__ETC___d272);
    if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d275)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32",
		     &__str_literal_9,
		     DEF_signed_0___d271,
		     DEF_signed_down_des_79_BITS_31_TO_0_80___d276);
    if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d279)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32",
		     &__str_literal_8,
		     DEF_signed_1___d280,
		     DEF_signed_2___d281);
    if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d284)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32",
		     &__str_literal_9,
		     DEF_signed_1___d280,
		     DEF_signed_0___d271);
    if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d287)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32",
		     &__str_literal_8,
		     DEF_signed_2___d281,
		     DEF_signed_up_des_56_BITS_95_TO_64_69___d288);
    if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d291)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32",
		     &__str_literal_9,
		     DEF_signed_2___d281,
		     DEF_signed_1___d280);
  }
  if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d251)
    INST_nextTest.METH_write((tUInt8)0u);
  if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d293)
    INST_c_direction.METH_write(DEF_direction_zaz_whas__0_AND_direction_zaz_wget__1___d52);
  if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d293)
    INST_current.METH_write(DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d302);
  if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d293)
    INST_up_pressed.METH_write(DEF__0_CONCAT_IF_floor_up_pressed_zaz_whas_THEN_flo_ETC___d304);
  if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d293)
    INST_down_pressed.METH_write(DEF_IF_floor_down_pressed_zaz_whas__4_THEN_floor_d_ETC___d306);
  if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d293)
    INST_up_des.METH_write(DEF_v__h1561);
  if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d293)
    INST_down_des.METH_write(DEF_v__h3642);
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d293)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_10, DEF_x__h16599);
  if (DEF_NOT_cycle_24_EQ_0_34_46_AND_NOT_cycle_24_EQ_12_ETC___d293)
    INST_tle.METH_write(0u);
}


/* Methods */


/* Reset routines */

void MOD_mkNextFloorStop::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_up_pressed.reset_RST(ARG_rst_in);
  INST_up_floor.reset_RST(ARG_rst_in);
  INST_up_des.reset_RST(ARG_rst_in);
  INST_tle.reset_RST(ARG_rst_in);
  INST_reset_des_reg.reset_RST(ARG_rst_in);
  INST_phase.reset_RST(ARG_rst_in);
  INST_nextTest.reset_RST(ARG_rst_in);
  INST_floor_up_pressed_initialized.reset_RST(ARG_rst_in);
  INST_floor_up_des_initialized.reset_RST(ARG_rst_in);
  INST_floor_down_pressed_initialized.reset_RST(ARG_rst_in);
  INST_floor_down_des_initialized.reset_RST(ARG_rst_in);
  INST_down_pressed.reset_RST(ARG_rst_in);
  INST_down_des.reset_RST(ARG_rst_in);
  INST_display.reset_RST(ARG_rst_in);
  INST_direction_initialized.reset_RST(ARG_rst_in);
  INST_des.reset_RST(ARG_rst_in);
  INST_cycle.reset_RST(ARG_rst_in);
  INST_currentFloor_initialized.reset_RST(ARG_rst_in);
  INST_current.reset_RST(ARG_rst_in);
  INST_c_direction.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkNextFloorStop::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkNextFloorStop::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_c_direction.dump_state(indent + 2u);
  INST_current.dump_state(indent + 2u);
  INST_currentFloor_ignore.dump_state(indent + 2u);
  INST_currentFloor_initialized.dump_state(indent + 2u);
  INST_currentFloor_zaz.dump_state(indent + 2u);
  INST_cycle.dump_state(indent + 2u);
  INST_des.dump_state(indent + 2u);
  INST_direction_ignore.dump_state(indent + 2u);
  INST_direction_initialized.dump_state(indent + 2u);
  INST_direction_zaz.dump_state(indent + 2u);
  INST_display.dump_state(indent + 2u);
  INST_down_des.dump_state(indent + 2u);
  INST_down_pressed.dump_state(indent + 2u);
  INST_floor_down_des_ignore.dump_state(indent + 2u);
  INST_floor_down_des_initialized.dump_state(indent + 2u);
  INST_floor_down_des_zaz.dump_state(indent + 2u);
  INST_floor_down_pressed_ignore.dump_state(indent + 2u);
  INST_floor_down_pressed_initialized.dump_state(indent + 2u);
  INST_floor_down_pressed_zaz.dump_state(indent + 2u);
  INST_floor_up_des_ignore.dump_state(indent + 2u);
  INST_floor_up_des_initialized.dump_state(indent + 2u);
  INST_floor_up_des_zaz.dump_state(indent + 2u);
  INST_floor_up_pressed_ignore.dump_state(indent + 2u);
  INST_floor_up_pressed_initialized.dump_state(indent + 2u);
  INST_floor_up_pressed_zaz.dump_state(indent + 2u);
  INST_nextTest.dump_state(indent + 2u);
  INST_phase.dump_state(indent + 2u);
  INST_reset_des_reg.dump_state(indent + 2u);
  INST_tle.dump_state(indent + 2u);
  INST_up_des.dump_state(indent + 2u);
  INST_up_floor.dump_state(indent + 2u);
  INST_up_pressed.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkNextFloorStop::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 102u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_c_direction_9___d117", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_current_0_EQ_0_1___d202", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_current_0_EQ_1_9___d200", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_current_0_EQ_2_5___d198", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_des_8_BIT_0_9___d130", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_des_8_BIT_1_0___d131", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_des_8_BIT_2_1___d132", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_down_pressed_1_BIT_0_2___d146", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_down_pressed_1_BIT_1_3___d147", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_down_pressed_1_BIT_2_4___d148", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_up_pressed_5_BIT_0_6___d135", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_up_pressed_5_BIT_1_7___d136", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_up_pressed_5_BIT_2_8___d137", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CO_ETC___d168", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "c_direction__h18832", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_24_EQ_0___d234", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_24_EQ_128___d235", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "des_BIT_0___h7812", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "des_BIT_1___h7845", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "des_BIT_2___h7878", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "des__h7877", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "direction_zaz_whas__0_AND_direction_zaz_wget__1___d52", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "display__h16295", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "down_des__h14338", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "down_pressed_BIT_0___h7539", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "down_pressed_BIT_1___h7572", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "down_pressed_BIT_2___h7605", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "down_pressed__h7604", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "new_value__h1523", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "new_value__h3604", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "new_value__h4538", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "up_des_BIT_31___h13787", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "up_des__h13868", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "up_pressed_BIT_0___h7267", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "up_pressed_BIT_1___h7300", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "up_pressed_BIT_2___h7333", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "up_pressed__h7332", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h13653", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1404", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h14224", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1442", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1480", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1561", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h2578", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h2658", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h327", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h3485", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h3523", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h3561", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h3642", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h408", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h4576", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h4902", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "value__h1564", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "value__h3645", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "value__h4579", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h13816", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h16446", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h16595", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h16599", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h1310", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h2521", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h262", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h3391", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h4402", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "y__h2298", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "y__h4178", 96u);
  num = INST_c_direction.dump_VCD_defs(num);
  num = INST_current.dump_VCD_defs(num);
  num = INST_currentFloor_ignore.dump_VCD_defs(num);
  num = INST_currentFloor_initialized.dump_VCD_defs(num);
  num = INST_currentFloor_zaz.dump_VCD_defs(num);
  num = INST_cycle.dump_VCD_defs(num);
  num = INST_des.dump_VCD_defs(num);
  num = INST_direction_ignore.dump_VCD_defs(num);
  num = INST_direction_initialized.dump_VCD_defs(num);
  num = INST_direction_zaz.dump_VCD_defs(num);
  num = INST_display.dump_VCD_defs(num);
  num = INST_down_des.dump_VCD_defs(num);
  num = INST_down_pressed.dump_VCD_defs(num);
  num = INST_floor_down_des_ignore.dump_VCD_defs(num);
  num = INST_floor_down_des_initialized.dump_VCD_defs(num);
  num = INST_floor_down_des_zaz.dump_VCD_defs(num);
  num = INST_floor_down_pressed_ignore.dump_VCD_defs(num);
  num = INST_floor_down_pressed_initialized.dump_VCD_defs(num);
  num = INST_floor_down_pressed_zaz.dump_VCD_defs(num);
  num = INST_floor_up_des_ignore.dump_VCD_defs(num);
  num = INST_floor_up_des_initialized.dump_VCD_defs(num);
  num = INST_floor_up_des_zaz.dump_VCD_defs(num);
  num = INST_floor_up_pressed_ignore.dump_VCD_defs(num);
  num = INST_floor_up_pressed_initialized.dump_VCD_defs(num);
  num = INST_floor_up_pressed_zaz.dump_VCD_defs(num);
  num = INST_nextTest.dump_VCD_defs(num);
  num = INST_phase.dump_VCD_defs(num);
  num = INST_reset_des_reg.dump_VCD_defs(num);
  num = INST_tle.dump_VCD_defs(num);
  num = INST_up_des.dump_VCD_defs(num);
  num = INST_up_floor.dump_VCD_defs(num);
  num = INST_up_pressed.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkNextFloorStop::dump_VCD(tVCDDumpType dt,
				   unsigned int levels,
				   MOD_mkNextFloorStop &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkNextFloorStop::vcd_defs(tVCDDumpType dt, MOD_mkNextFloorStop &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 96u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164) != DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164, 32u);
	backing.DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164 = DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164;
      }
      ++num;
      if ((backing.DEF_NOT_c_direction_9___d117) != DEF_NOT_c_direction_9___d117)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_c_direction_9___d117, 1u);
	backing.DEF_NOT_c_direction_9___d117 = DEF_NOT_c_direction_9___d117;
      }
      ++num;
      if ((backing.DEF_NOT_current_0_EQ_0_1___d202) != DEF_NOT_current_0_EQ_0_1___d202)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_current_0_EQ_0_1___d202, 1u);
	backing.DEF_NOT_current_0_EQ_0_1___d202 = DEF_NOT_current_0_EQ_0_1___d202;
      }
      ++num;
      if ((backing.DEF_NOT_current_0_EQ_1_9___d200) != DEF_NOT_current_0_EQ_1_9___d200)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_current_0_EQ_1_9___d200, 1u);
	backing.DEF_NOT_current_0_EQ_1_9___d200 = DEF_NOT_current_0_EQ_1_9___d200;
      }
      ++num;
      if ((backing.DEF_NOT_current_0_EQ_2_5___d198) != DEF_NOT_current_0_EQ_2_5___d198)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_current_0_EQ_2_5___d198, 1u);
	backing.DEF_NOT_current_0_EQ_2_5___d198 = DEF_NOT_current_0_EQ_2_5___d198;
      }
      ++num;
      if ((backing.DEF_NOT_des_8_BIT_0_9___d130) != DEF_NOT_des_8_BIT_0_9___d130)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_des_8_BIT_0_9___d130, 1u);
	backing.DEF_NOT_des_8_BIT_0_9___d130 = DEF_NOT_des_8_BIT_0_9___d130;
      }
      ++num;
      if ((backing.DEF_NOT_des_8_BIT_1_0___d131) != DEF_NOT_des_8_BIT_1_0___d131)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_des_8_BIT_1_0___d131, 1u);
	backing.DEF_NOT_des_8_BIT_1_0___d131 = DEF_NOT_des_8_BIT_1_0___d131;
      }
      ++num;
      if ((backing.DEF_NOT_des_8_BIT_2_1___d132) != DEF_NOT_des_8_BIT_2_1___d132)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_des_8_BIT_2_1___d132, 1u);
	backing.DEF_NOT_des_8_BIT_2_1___d132 = DEF_NOT_des_8_BIT_2_1___d132;
      }
      ++num;
      if ((backing.DEF_NOT_down_pressed_1_BIT_0_2___d146) != DEF_NOT_down_pressed_1_BIT_0_2___d146)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_down_pressed_1_BIT_0_2___d146, 1u);
	backing.DEF_NOT_down_pressed_1_BIT_0_2___d146 = DEF_NOT_down_pressed_1_BIT_0_2___d146;
      }
      ++num;
      if ((backing.DEF_NOT_down_pressed_1_BIT_1_3___d147) != DEF_NOT_down_pressed_1_BIT_1_3___d147)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_down_pressed_1_BIT_1_3___d147, 1u);
	backing.DEF_NOT_down_pressed_1_BIT_1_3___d147 = DEF_NOT_down_pressed_1_BIT_1_3___d147;
      }
      ++num;
      if ((backing.DEF_NOT_down_pressed_1_BIT_2_4___d148) != DEF_NOT_down_pressed_1_BIT_2_4___d148)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_down_pressed_1_BIT_2_4___d148, 1u);
	backing.DEF_NOT_down_pressed_1_BIT_2_4___d148 = DEF_NOT_down_pressed_1_BIT_2_4___d148;
      }
      ++num;
      if ((backing.DEF_NOT_up_pressed_5_BIT_0_6___d135) != DEF_NOT_up_pressed_5_BIT_0_6___d135)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_up_pressed_5_BIT_0_6___d135, 1u);
	backing.DEF_NOT_up_pressed_5_BIT_0_6___d135 = DEF_NOT_up_pressed_5_BIT_0_6___d135;
      }
      ++num;
      if ((backing.DEF_NOT_up_pressed_5_BIT_1_7___d136) != DEF_NOT_up_pressed_5_BIT_1_7___d136)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_up_pressed_5_BIT_1_7___d136, 1u);
	backing.DEF_NOT_up_pressed_5_BIT_1_7___d136 = DEF_NOT_up_pressed_5_BIT_1_7___d136;
      }
      ++num;
      if ((backing.DEF_NOT_up_pressed_5_BIT_2_8___d137) != DEF_NOT_up_pressed_5_BIT_2_8___d137)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_up_pressed_5_BIT_2_8___d137, 1u);
	backing.DEF_NOT_up_pressed_5_BIT_2_8___d137 = DEF_NOT_up_pressed_5_BIT_2_8___d137;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162) != DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162)
      {
	vcd_write_val(sim_hdl, num, DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162, 32u);
	backing.DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162 = DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162;
      }
      ++num;
      if ((backing.DEF__1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CO_ETC___d168) != DEF__1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CO_ETC___d168)
      {
	vcd_write_val(sim_hdl, num, DEF__1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CO_ETC___d168, 32u);
	backing.DEF__1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CO_ETC___d168 = DEF__1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CO_ETC___d168;
      }
      ++num;
      if ((backing.DEF_c_direction__h18832) != DEF_c_direction__h18832)
      {
	vcd_write_val(sim_hdl, num, DEF_c_direction__h18832, 1u);
	backing.DEF_c_direction__h18832 = DEF_c_direction__h18832;
      }
      ++num;
      if ((backing.DEF_cycle_24_EQ_0___d234) != DEF_cycle_24_EQ_0___d234)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_24_EQ_0___d234, 1u);
	backing.DEF_cycle_24_EQ_0___d234 = DEF_cycle_24_EQ_0___d234;
      }
      ++num;
      if ((backing.DEF_cycle_24_EQ_128___d235) != DEF_cycle_24_EQ_128___d235)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_24_EQ_128___d235, 1u);
	backing.DEF_cycle_24_EQ_128___d235 = DEF_cycle_24_EQ_128___d235;
      }
      ++num;
      if ((backing.DEF_des_BIT_0___h7812) != DEF_des_BIT_0___h7812)
      {
	vcd_write_val(sim_hdl, num, DEF_des_BIT_0___h7812, 1u);
	backing.DEF_des_BIT_0___h7812 = DEF_des_BIT_0___h7812;
      }
      ++num;
      if ((backing.DEF_des_BIT_1___h7845) != DEF_des_BIT_1___h7845)
      {
	vcd_write_val(sim_hdl, num, DEF_des_BIT_1___h7845, 1u);
	backing.DEF_des_BIT_1___h7845 = DEF_des_BIT_1___h7845;
      }
      ++num;
      if ((backing.DEF_des_BIT_2___h7878) != DEF_des_BIT_2___h7878)
      {
	vcd_write_val(sim_hdl, num, DEF_des_BIT_2___h7878, 1u);
	backing.DEF_des_BIT_2___h7878 = DEF_des_BIT_2___h7878;
      }
      ++num;
      if ((backing.DEF_des__h7877) != DEF_des__h7877)
      {
	vcd_write_val(sim_hdl, num, DEF_des__h7877, 3u);
	backing.DEF_des__h7877 = DEF_des__h7877;
      }
      ++num;
      if ((backing.DEF_direction_zaz_whas__0_AND_direction_zaz_wget__1___d52) != DEF_direction_zaz_whas__0_AND_direction_zaz_wget__1___d52)
      {
	vcd_write_val(sim_hdl, num, DEF_direction_zaz_whas__0_AND_direction_zaz_wget__1___d52, 1u);
	backing.DEF_direction_zaz_whas__0_AND_direction_zaz_wget__1___d52 = DEF_direction_zaz_whas__0_AND_direction_zaz_wget__1___d52;
      }
      ++num;
      if ((backing.DEF_display__h16295) != DEF_display__h16295)
      {
	vcd_write_val(sim_hdl, num, DEF_display__h16295, 1u);
	backing.DEF_display__h16295 = DEF_display__h16295;
      }
      ++num;
      if ((backing.DEF_down_des__h14338) != DEF_down_des__h14338)
      {
	vcd_write_val(sim_hdl, num, DEF_down_des__h14338, 96u);
	backing.DEF_down_des__h14338 = DEF_down_des__h14338;
      }
      ++num;
      if ((backing.DEF_down_pressed_BIT_0___h7539) != DEF_down_pressed_BIT_0___h7539)
      {
	vcd_write_val(sim_hdl, num, DEF_down_pressed_BIT_0___h7539, 1u);
	backing.DEF_down_pressed_BIT_0___h7539 = DEF_down_pressed_BIT_0___h7539;
      }
      ++num;
      if ((backing.DEF_down_pressed_BIT_1___h7572) != DEF_down_pressed_BIT_1___h7572)
      {
	vcd_write_val(sim_hdl, num, DEF_down_pressed_BIT_1___h7572, 1u);
	backing.DEF_down_pressed_BIT_1___h7572 = DEF_down_pressed_BIT_1___h7572;
      }
      ++num;
      if ((backing.DEF_down_pressed_BIT_2___h7605) != DEF_down_pressed_BIT_2___h7605)
      {
	vcd_write_val(sim_hdl, num, DEF_down_pressed_BIT_2___h7605, 1u);
	backing.DEF_down_pressed_BIT_2___h7605 = DEF_down_pressed_BIT_2___h7605;
      }
      ++num;
      if ((backing.DEF_down_pressed__h7604) != DEF_down_pressed__h7604)
      {
	vcd_write_val(sim_hdl, num, DEF_down_pressed__h7604, 3u);
	backing.DEF_down_pressed__h7604 = DEF_down_pressed__h7604;
      }
      ++num;
      if ((backing.DEF_new_value__h1523) != DEF_new_value__h1523)
      {
	vcd_write_val(sim_hdl, num, DEF_new_value__h1523, 96u);
	backing.DEF_new_value__h1523 = DEF_new_value__h1523;
      }
      ++num;
      if ((backing.DEF_new_value__h3604) != DEF_new_value__h3604)
      {
	vcd_write_val(sim_hdl, num, DEF_new_value__h3604, 96u);
	backing.DEF_new_value__h3604 = DEF_new_value__h3604;
      }
      ++num;
      if ((backing.DEF_new_value__h4538) != DEF_new_value__h4538)
      {
	vcd_write_val(sim_hdl, num, DEF_new_value__h4538, 32u);
	backing.DEF_new_value__h4538 = DEF_new_value__h4538;
      }
      ++num;
      if ((backing.DEF_up_des_BIT_31___h13787) != DEF_up_des_BIT_31___h13787)
      {
	vcd_write_val(sim_hdl, num, DEF_up_des_BIT_31___h13787, 1u);
	backing.DEF_up_des_BIT_31___h13787 = DEF_up_des_BIT_31___h13787;
      }
      ++num;
      if ((backing.DEF_up_des__h13868) != DEF_up_des__h13868)
      {
	vcd_write_val(sim_hdl, num, DEF_up_des__h13868, 96u);
	backing.DEF_up_des__h13868 = DEF_up_des__h13868;
      }
      ++num;
      if ((backing.DEF_up_pressed_BIT_0___h7267) != DEF_up_pressed_BIT_0___h7267)
      {
	vcd_write_val(sim_hdl, num, DEF_up_pressed_BIT_0___h7267, 1u);
	backing.DEF_up_pressed_BIT_0___h7267 = DEF_up_pressed_BIT_0___h7267;
      }
      ++num;
      if ((backing.DEF_up_pressed_BIT_1___h7300) != DEF_up_pressed_BIT_1___h7300)
      {
	vcd_write_val(sim_hdl, num, DEF_up_pressed_BIT_1___h7300, 1u);
	backing.DEF_up_pressed_BIT_1___h7300 = DEF_up_pressed_BIT_1___h7300;
      }
      ++num;
      if ((backing.DEF_up_pressed_BIT_2___h7333) != DEF_up_pressed_BIT_2___h7333)
      {
	vcd_write_val(sim_hdl, num, DEF_up_pressed_BIT_2___h7333, 1u);
	backing.DEF_up_pressed_BIT_2___h7333 = DEF_up_pressed_BIT_2___h7333;
      }
      ++num;
      if ((backing.DEF_up_pressed__h7332) != DEF_up_pressed__h7332)
      {
	vcd_write_val(sim_hdl, num, DEF_up_pressed__h7332, 3u);
	backing.DEF_up_pressed__h7332 = DEF_up_pressed__h7332;
      }
      ++num;
      if ((backing.DEF_v__h13653) != DEF_v__h13653)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h13653, 32u);
	backing.DEF_v__h13653 = DEF_v__h13653;
      }
      ++num;
      if ((backing.DEF_v__h1404) != DEF_v__h1404)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1404, 32u);
	backing.DEF_v__h1404 = DEF_v__h1404;
      }
      ++num;
      if ((backing.DEF_v__h14224) != DEF_v__h14224)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h14224, 32u);
	backing.DEF_v__h14224 = DEF_v__h14224;
      }
      ++num;
      if ((backing.DEF_v__h1442) != DEF_v__h1442)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1442, 32u);
	backing.DEF_v__h1442 = DEF_v__h1442;
      }
      ++num;
      if ((backing.DEF_v__h1480) != DEF_v__h1480)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1480, 32u);
	backing.DEF_v__h1480 = DEF_v__h1480;
      }
      ++num;
      if ((backing.DEF_v__h1561) != DEF_v__h1561)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1561, 96u);
	backing.DEF_v__h1561 = DEF_v__h1561;
      }
      ++num;
      if ((backing.DEF_v__h2578) != DEF_v__h2578)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h2578, 32u);
	backing.DEF_v__h2578 = DEF_v__h2578;
      }
      ++num;
      if ((backing.DEF_v__h2658) != DEF_v__h2658)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h2658, 3u);
	backing.DEF_v__h2658 = DEF_v__h2658;
      }
      ++num;
      if ((backing.DEF_v__h327) != DEF_v__h327)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h327, 32u);
	backing.DEF_v__h327 = DEF_v__h327;
      }
      ++num;
      if ((backing.DEF_v__h3485) != DEF_v__h3485)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h3485, 32u);
	backing.DEF_v__h3485 = DEF_v__h3485;
      }
      ++num;
      if ((backing.DEF_v__h3523) != DEF_v__h3523)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h3523, 32u);
	backing.DEF_v__h3523 = DEF_v__h3523;
      }
      ++num;
      if ((backing.DEF_v__h3561) != DEF_v__h3561)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h3561, 32u);
	backing.DEF_v__h3561 = DEF_v__h3561;
      }
      ++num;
      if ((backing.DEF_v__h3642) != DEF_v__h3642)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h3642, 96u);
	backing.DEF_v__h3642 = DEF_v__h3642;
      }
      ++num;
      if ((backing.DEF_v__h408) != DEF_v__h408)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h408, 3u);
	backing.DEF_v__h408 = DEF_v__h408;
      }
      ++num;
      if ((backing.DEF_v__h4576) != DEF_v__h4576)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h4576, 32u);
	backing.DEF_v__h4576 = DEF_v__h4576;
      }
      ++num;
      if ((backing.DEF_v__h4902) != DEF_v__h4902)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h4902, 32u);
	backing.DEF_v__h4902 = DEF_v__h4902;
      }
      ++num;
      if ((backing.DEF_value__h1564) != DEF_value__h1564)
      {
	vcd_write_val(sim_hdl, num, DEF_value__h1564, 96u);
	backing.DEF_value__h1564 = DEF_value__h1564;
      }
      ++num;
      if ((backing.DEF_value__h3645) != DEF_value__h3645)
      {
	vcd_write_val(sim_hdl, num, DEF_value__h3645, 96u);
	backing.DEF_value__h3645 = DEF_value__h3645;
      }
      ++num;
      if ((backing.DEF_value__h4579) != DEF_value__h4579)
      {
	vcd_write_val(sim_hdl, num, DEF_value__h4579, 32u);
	backing.DEF_value__h4579 = DEF_value__h4579;
      }
      ++num;
      if ((backing.DEF_x__h13816) != DEF_x__h13816)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h13816, 32u);
	backing.DEF_x__h13816 = DEF_x__h13816;
      }
      ++num;
      if ((backing.DEF_x__h16446) != DEF_x__h16446)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h16446, 32u);
	backing.DEF_x__h16446 = DEF_x__h16446;
      }
      ++num;
      if ((backing.DEF_x__h16595) != DEF_x__h16595)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h16595, 32u);
	backing.DEF_x__h16595 = DEF_x__h16595;
      }
      ++num;
      if ((backing.DEF_x__h16599) != DEF_x__h16599)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h16599, 32u);
	backing.DEF_x__h16599 = DEF_x__h16599;
      }
      ++num;
      if ((backing.DEF_x_wget__h1310) != DEF_x_wget__h1310)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h1310, 96u);
	backing.DEF_x_wget__h1310 = DEF_x_wget__h1310;
      }
      ++num;
      if ((backing.DEF_x_wget__h2521) != DEF_x_wget__h2521)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h2521, 3u);
	backing.DEF_x_wget__h2521 = DEF_x_wget__h2521;
      }
      ++num;
      if ((backing.DEF_x_wget__h262) != DEF_x_wget__h262)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h262, 3u);
	backing.DEF_x_wget__h262 = DEF_x_wget__h262;
      }
      ++num;
      if ((backing.DEF_x_wget__h3391) != DEF_x_wget__h3391)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h3391, 96u);
	backing.DEF_x_wget__h3391 = DEF_x_wget__h3391;
      }
      ++num;
      if ((backing.DEF_x_wget__h4402) != DEF_x_wget__h4402)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h4402, 32u);
	backing.DEF_x_wget__h4402 = DEF_x_wget__h4402;
      }
      ++num;
      if ((backing.DEF_y__h2298) != DEF_y__h2298)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h2298, 96u);
	backing.DEF_y__h2298 = DEF_y__h2298;
      }
      ++num;
      if ((backing.DEF_y__h4178) != DEF_y__h4178)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h4178, 96u);
	backing.DEF_y__h4178 = DEF_y__h4178;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164, 32u);
      backing.DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164 = DEF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CONCAT_IF_up_ETC___d164;
      vcd_write_val(sim_hdl, num++, DEF_NOT_c_direction_9___d117, 1u);
      backing.DEF_NOT_c_direction_9___d117 = DEF_NOT_c_direction_9___d117;
      vcd_write_val(sim_hdl, num++, DEF_NOT_current_0_EQ_0_1___d202, 1u);
      backing.DEF_NOT_current_0_EQ_0_1___d202 = DEF_NOT_current_0_EQ_0_1___d202;
      vcd_write_val(sim_hdl, num++, DEF_NOT_current_0_EQ_1_9___d200, 1u);
      backing.DEF_NOT_current_0_EQ_1_9___d200 = DEF_NOT_current_0_EQ_1_9___d200;
      vcd_write_val(sim_hdl, num++, DEF_NOT_current_0_EQ_2_5___d198, 1u);
      backing.DEF_NOT_current_0_EQ_2_5___d198 = DEF_NOT_current_0_EQ_2_5___d198;
      vcd_write_val(sim_hdl, num++, DEF_NOT_des_8_BIT_0_9___d130, 1u);
      backing.DEF_NOT_des_8_BIT_0_9___d130 = DEF_NOT_des_8_BIT_0_9___d130;
      vcd_write_val(sim_hdl, num++, DEF_NOT_des_8_BIT_1_0___d131, 1u);
      backing.DEF_NOT_des_8_BIT_1_0___d131 = DEF_NOT_des_8_BIT_1_0___d131;
      vcd_write_val(sim_hdl, num++, DEF_NOT_des_8_BIT_2_1___d132, 1u);
      backing.DEF_NOT_des_8_BIT_2_1___d132 = DEF_NOT_des_8_BIT_2_1___d132;
      vcd_write_val(sim_hdl, num++, DEF_NOT_down_pressed_1_BIT_0_2___d146, 1u);
      backing.DEF_NOT_down_pressed_1_BIT_0_2___d146 = DEF_NOT_down_pressed_1_BIT_0_2___d146;
      vcd_write_val(sim_hdl, num++, DEF_NOT_down_pressed_1_BIT_1_3___d147, 1u);
      backing.DEF_NOT_down_pressed_1_BIT_1_3___d147 = DEF_NOT_down_pressed_1_BIT_1_3___d147;
      vcd_write_val(sim_hdl, num++, DEF_NOT_down_pressed_1_BIT_2_4___d148, 1u);
      backing.DEF_NOT_down_pressed_1_BIT_2_4___d148 = DEF_NOT_down_pressed_1_BIT_2_4___d148;
      vcd_write_val(sim_hdl, num++, DEF_NOT_up_pressed_5_BIT_0_6___d135, 1u);
      backing.DEF_NOT_up_pressed_5_BIT_0_6___d135 = DEF_NOT_up_pressed_5_BIT_0_6___d135;
      vcd_write_val(sim_hdl, num++, DEF_NOT_up_pressed_5_BIT_1_7___d136, 1u);
      backing.DEF_NOT_up_pressed_5_BIT_1_7___d136 = DEF_NOT_up_pressed_5_BIT_1_7___d136;
      vcd_write_val(sim_hdl, num++, DEF_NOT_up_pressed_5_BIT_2_8___d137, 1u);
      backing.DEF_NOT_up_pressed_5_BIT_2_8___d137 = DEF_NOT_up_pressed_5_BIT_2_8___d137;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162, 32u);
      backing.DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162 = DEF__0_CONCAT_IF_up_des_56_BIT_31_57_THEN_NEG_up_de_ETC___d162;
      vcd_write_val(sim_hdl, num++, DEF__1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CO_ETC___d168, 32u);
      backing.DEF__1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CO_ETC___d168 = DEF__1_PLUS_IF_IF_up_des_56_BIT_31_57_THEN_NEG_0_CO_ETC___d168;
      vcd_write_val(sim_hdl, num++, DEF_c_direction__h18832, 1u);
      backing.DEF_c_direction__h18832 = DEF_c_direction__h18832;
      vcd_write_val(sim_hdl, num++, DEF_cycle_24_EQ_0___d234, 1u);
      backing.DEF_cycle_24_EQ_0___d234 = DEF_cycle_24_EQ_0___d234;
      vcd_write_val(sim_hdl, num++, DEF_cycle_24_EQ_128___d235, 1u);
      backing.DEF_cycle_24_EQ_128___d235 = DEF_cycle_24_EQ_128___d235;
      vcd_write_val(sim_hdl, num++, DEF_des_BIT_0___h7812, 1u);
      backing.DEF_des_BIT_0___h7812 = DEF_des_BIT_0___h7812;
      vcd_write_val(sim_hdl, num++, DEF_des_BIT_1___h7845, 1u);
      backing.DEF_des_BIT_1___h7845 = DEF_des_BIT_1___h7845;
      vcd_write_val(sim_hdl, num++, DEF_des_BIT_2___h7878, 1u);
      backing.DEF_des_BIT_2___h7878 = DEF_des_BIT_2___h7878;
      vcd_write_val(sim_hdl, num++, DEF_des__h7877, 3u);
      backing.DEF_des__h7877 = DEF_des__h7877;
      vcd_write_val(sim_hdl, num++, DEF_direction_zaz_whas__0_AND_direction_zaz_wget__1___d52, 1u);
      backing.DEF_direction_zaz_whas__0_AND_direction_zaz_wget__1___d52 = DEF_direction_zaz_whas__0_AND_direction_zaz_wget__1___d52;
      vcd_write_val(sim_hdl, num++, DEF_display__h16295, 1u);
      backing.DEF_display__h16295 = DEF_display__h16295;
      vcd_write_val(sim_hdl, num++, DEF_down_des__h14338, 96u);
      backing.DEF_down_des__h14338 = DEF_down_des__h14338;
      vcd_write_val(sim_hdl, num++, DEF_down_pressed_BIT_0___h7539, 1u);
      backing.DEF_down_pressed_BIT_0___h7539 = DEF_down_pressed_BIT_0___h7539;
      vcd_write_val(sim_hdl, num++, DEF_down_pressed_BIT_1___h7572, 1u);
      backing.DEF_down_pressed_BIT_1___h7572 = DEF_down_pressed_BIT_1___h7572;
      vcd_write_val(sim_hdl, num++, DEF_down_pressed_BIT_2___h7605, 1u);
      backing.DEF_down_pressed_BIT_2___h7605 = DEF_down_pressed_BIT_2___h7605;
      vcd_write_val(sim_hdl, num++, DEF_down_pressed__h7604, 3u);
      backing.DEF_down_pressed__h7604 = DEF_down_pressed__h7604;
      vcd_write_val(sim_hdl, num++, DEF_new_value__h1523, 96u);
      backing.DEF_new_value__h1523 = DEF_new_value__h1523;
      vcd_write_val(sim_hdl, num++, DEF_new_value__h3604, 96u);
      backing.DEF_new_value__h3604 = DEF_new_value__h3604;
      vcd_write_val(sim_hdl, num++, DEF_new_value__h4538, 32u);
      backing.DEF_new_value__h4538 = DEF_new_value__h4538;
      vcd_write_val(sim_hdl, num++, DEF_up_des_BIT_31___h13787, 1u);
      backing.DEF_up_des_BIT_31___h13787 = DEF_up_des_BIT_31___h13787;
      vcd_write_val(sim_hdl, num++, DEF_up_des__h13868, 96u);
      backing.DEF_up_des__h13868 = DEF_up_des__h13868;
      vcd_write_val(sim_hdl, num++, DEF_up_pressed_BIT_0___h7267, 1u);
      backing.DEF_up_pressed_BIT_0___h7267 = DEF_up_pressed_BIT_0___h7267;
      vcd_write_val(sim_hdl, num++, DEF_up_pressed_BIT_1___h7300, 1u);
      backing.DEF_up_pressed_BIT_1___h7300 = DEF_up_pressed_BIT_1___h7300;
      vcd_write_val(sim_hdl, num++, DEF_up_pressed_BIT_2___h7333, 1u);
      backing.DEF_up_pressed_BIT_2___h7333 = DEF_up_pressed_BIT_2___h7333;
      vcd_write_val(sim_hdl, num++, DEF_up_pressed__h7332, 3u);
      backing.DEF_up_pressed__h7332 = DEF_up_pressed__h7332;
      vcd_write_val(sim_hdl, num++, DEF_v__h13653, 32u);
      backing.DEF_v__h13653 = DEF_v__h13653;
      vcd_write_val(sim_hdl, num++, DEF_v__h1404, 32u);
      backing.DEF_v__h1404 = DEF_v__h1404;
      vcd_write_val(sim_hdl, num++, DEF_v__h14224, 32u);
      backing.DEF_v__h14224 = DEF_v__h14224;
      vcd_write_val(sim_hdl, num++, DEF_v__h1442, 32u);
      backing.DEF_v__h1442 = DEF_v__h1442;
      vcd_write_val(sim_hdl, num++, DEF_v__h1480, 32u);
      backing.DEF_v__h1480 = DEF_v__h1480;
      vcd_write_val(sim_hdl, num++, DEF_v__h1561, 96u);
      backing.DEF_v__h1561 = DEF_v__h1561;
      vcd_write_val(sim_hdl, num++, DEF_v__h2578, 32u);
      backing.DEF_v__h2578 = DEF_v__h2578;
      vcd_write_val(sim_hdl, num++, DEF_v__h2658, 3u);
      backing.DEF_v__h2658 = DEF_v__h2658;
      vcd_write_val(sim_hdl, num++, DEF_v__h327, 32u);
      backing.DEF_v__h327 = DEF_v__h327;
      vcd_write_val(sim_hdl, num++, DEF_v__h3485, 32u);
      backing.DEF_v__h3485 = DEF_v__h3485;
      vcd_write_val(sim_hdl, num++, DEF_v__h3523, 32u);
      backing.DEF_v__h3523 = DEF_v__h3523;
      vcd_write_val(sim_hdl, num++, DEF_v__h3561, 32u);
      backing.DEF_v__h3561 = DEF_v__h3561;
      vcd_write_val(sim_hdl, num++, DEF_v__h3642, 96u);
      backing.DEF_v__h3642 = DEF_v__h3642;
      vcd_write_val(sim_hdl, num++, DEF_v__h408, 3u);
      backing.DEF_v__h408 = DEF_v__h408;
      vcd_write_val(sim_hdl, num++, DEF_v__h4576, 32u);
      backing.DEF_v__h4576 = DEF_v__h4576;
      vcd_write_val(sim_hdl, num++, DEF_v__h4902, 32u);
      backing.DEF_v__h4902 = DEF_v__h4902;
      vcd_write_val(sim_hdl, num++, DEF_value__h1564, 96u);
      backing.DEF_value__h1564 = DEF_value__h1564;
      vcd_write_val(sim_hdl, num++, DEF_value__h3645, 96u);
      backing.DEF_value__h3645 = DEF_value__h3645;
      vcd_write_val(sim_hdl, num++, DEF_value__h4579, 32u);
      backing.DEF_value__h4579 = DEF_value__h4579;
      vcd_write_val(sim_hdl, num++, DEF_x__h13816, 32u);
      backing.DEF_x__h13816 = DEF_x__h13816;
      vcd_write_val(sim_hdl, num++, DEF_x__h16446, 32u);
      backing.DEF_x__h16446 = DEF_x__h16446;
      vcd_write_val(sim_hdl, num++, DEF_x__h16595, 32u);
      backing.DEF_x__h16595 = DEF_x__h16595;
      vcd_write_val(sim_hdl, num++, DEF_x__h16599, 32u);
      backing.DEF_x__h16599 = DEF_x__h16599;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h1310, 96u);
      backing.DEF_x_wget__h1310 = DEF_x_wget__h1310;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h2521, 3u);
      backing.DEF_x_wget__h2521 = DEF_x_wget__h2521;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h262, 3u);
      backing.DEF_x_wget__h262 = DEF_x_wget__h262;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h3391, 96u);
      backing.DEF_x_wget__h3391 = DEF_x_wget__h3391;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h4402, 32u);
      backing.DEF_x_wget__h4402 = DEF_x_wget__h4402;
      vcd_write_val(sim_hdl, num++, DEF_y__h2298, 96u);
      backing.DEF_y__h2298 = DEF_y__h2298;
      vcd_write_val(sim_hdl, num++, DEF_y__h4178, 96u);
      backing.DEF_y__h4178 = DEF_y__h4178;
    }
}

void MOD_mkNextFloorStop::vcd_prims(tVCDDumpType dt, MOD_mkNextFloorStop &backing)
{
  INST_c_direction.dump_VCD(dt, backing.INST_c_direction);
  INST_current.dump_VCD(dt, backing.INST_current);
  INST_currentFloor_ignore.dump_VCD(dt, backing.INST_currentFloor_ignore);
  INST_currentFloor_initialized.dump_VCD(dt, backing.INST_currentFloor_initialized);
  INST_currentFloor_zaz.dump_VCD(dt, backing.INST_currentFloor_zaz);
  INST_cycle.dump_VCD(dt, backing.INST_cycle);
  INST_des.dump_VCD(dt, backing.INST_des);
  INST_direction_ignore.dump_VCD(dt, backing.INST_direction_ignore);
  INST_direction_initialized.dump_VCD(dt, backing.INST_direction_initialized);
  INST_direction_zaz.dump_VCD(dt, backing.INST_direction_zaz);
  INST_display.dump_VCD(dt, backing.INST_display);
  INST_down_des.dump_VCD(dt, backing.INST_down_des);
  INST_down_pressed.dump_VCD(dt, backing.INST_down_pressed);
  INST_floor_down_des_ignore.dump_VCD(dt, backing.INST_floor_down_des_ignore);
  INST_floor_down_des_initialized.dump_VCD(dt, backing.INST_floor_down_des_initialized);
  INST_floor_down_des_zaz.dump_VCD(dt, backing.INST_floor_down_des_zaz);
  INST_floor_down_pressed_ignore.dump_VCD(dt, backing.INST_floor_down_pressed_ignore);
  INST_floor_down_pressed_initialized.dump_VCD(dt, backing.INST_floor_down_pressed_initialized);
  INST_floor_down_pressed_zaz.dump_VCD(dt, backing.INST_floor_down_pressed_zaz);
  INST_floor_up_des_ignore.dump_VCD(dt, backing.INST_floor_up_des_ignore);
  INST_floor_up_des_initialized.dump_VCD(dt, backing.INST_floor_up_des_initialized);
  INST_floor_up_des_zaz.dump_VCD(dt, backing.INST_floor_up_des_zaz);
  INST_floor_up_pressed_ignore.dump_VCD(dt, backing.INST_floor_up_pressed_ignore);
  INST_floor_up_pressed_initialized.dump_VCD(dt, backing.INST_floor_up_pressed_initialized);
  INST_floor_up_pressed_zaz.dump_VCD(dt, backing.INST_floor_up_pressed_zaz);
  INST_nextTest.dump_VCD(dt, backing.INST_nextTest);
  INST_phase.dump_VCD(dt, backing.INST_phase);
  INST_reset_des_reg.dump_VCD(dt, backing.INST_reset_des_reg);
  INST_tle.dump_VCD(dt, backing.INST_tle);
  INST_up_des.dump_VCD(dt, backing.INST_up_des);
  INST_up_floor.dump_VCD(dt, backing.INST_up_floor);
  INST_up_pressed.dump_VCD(dt, backing.INST_up_pressed);
}
