/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Thu Mar  9 20:52:41 PST 2017
 * 
 */
#include "bluesim_primitives.h"
#include "mkNextFloorUpStop.h"
#include "imported_BDPI_functions.h"


/* String declarations */
static std::string const __str_literal_7("Expected=%d, Your answer=%d", 27u);
static std::string const __str_literal_2("FAIL %d", 7u);
static std::string const __str_literal_1("PASSED", 6u);
static std::string const __str_literal_6("currentFloor=%d", 15u);
static std::string const __str_literal_5("floor_des[%d]=%b", 16u);
static std::string const __str_literal_4("floor_down_pressed[%d]=%b", 25u);
static std::string const __str_literal_3("floor_up_pressed[%d]=%b", 23u);


/* Constructor */
MOD_mkNextFloorUpStop::MOD_mkNextFloorUpStop(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_currentFloor_ignore(simHdl, "currentFloor_ignore", this, 32u, (tUInt8)0u),
    INST_currentFloor_initialized(simHdl, "currentFloor_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_currentFloor_zaz(simHdl, "currentFloor_zaz", this, 32u, (tUInt8)0u),
    INST_cycle(simHdl, "cycle", this, 32u, 0u, (tUInt8)0u),
    INST_floor_des_ignore(simHdl, "floor_des_ignore", this, 3u, (tUInt8)0u),
    INST_floor_des_initialized(simHdl, "floor_des_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_floor_des_zaz(simHdl, "floor_des_zaz", this, 3u, (tUInt8)0u),
    INST_floor_down_pressed_ignore(simHdl, "floor_down_pressed_ignore", this, 3u, (tUInt8)0u),
    INST_floor_down_pressed_initialized(simHdl,
					"floor_down_pressed_initialized",
					this,
					1u,
					(tUInt8)0u,
					(tUInt8)0u),
    INST_floor_down_pressed_zaz(simHdl, "floor_down_pressed_zaz", this, 3u, (tUInt8)0u),
    INST_floor_up_pressed_ignore(simHdl, "floor_up_pressed_ignore", this, 3u, (tUInt8)0u),
    INST_floor_up_pressed_initialized(simHdl,
				      "floor_up_pressed_initialized",
				      this,
				      1u,
				      (tUInt8)0u,
				      (tUInt8)0u),
    INST_floor_up_pressed_zaz(simHdl, "floor_up_pressed_zaz", this, 3u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_new_value__h3178(2863311530u),
    DEF_v__h2228(2863311530u),
    DEF_v__h1358(2863311530u),
    DEF_v__h318(2863311530u)
{
  symbol_count = 31u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkNextFloorUpStop::init_symbols_0()
{
  init_symbol(&symbols[0u], "currentFloor_ignore", SYM_MODULE, &INST_currentFloor_ignore);
  init_symbol(&symbols[1u], "currentFloor_initialized", SYM_MODULE, &INST_currentFloor_initialized);
  init_symbol(&symbols[2u], "currentFloor_zaz", SYM_MODULE, &INST_currentFloor_zaz);
  init_symbol(&symbols[3u], "cycle", SYM_MODULE, &INST_cycle);
  init_symbol(&symbols[4u], "floor_des_ignore", SYM_MODULE, &INST_floor_des_ignore);
  init_symbol(&symbols[5u], "floor_des_initialized", SYM_MODULE, &INST_floor_des_initialized);
  init_symbol(&symbols[6u], "floor_des_zaz", SYM_MODULE, &INST_floor_des_zaz);
  init_symbol(&symbols[7u], "floor_down_pressed_ignore", SYM_MODULE, &INST_floor_down_pressed_ignore);
  init_symbol(&symbols[8u],
	      "floor_down_pressed_initialized",
	      SYM_MODULE,
	      &INST_floor_down_pressed_initialized);
  init_symbol(&symbols[9u], "floor_down_pressed_zaz", SYM_MODULE, &INST_floor_down_pressed_zaz);
  init_symbol(&symbols[10u], "floor_up_pressed_ignore", SYM_MODULE, &INST_floor_up_pressed_ignore);
  init_symbol(&symbols[11u],
	      "floor_up_pressed_initialized",
	      SYM_MODULE,
	      &INST_floor_up_pressed_initialized);
  init_symbol(&symbols[12u], "floor_up_pressed_zaz", SYM_MODULE, &INST_floor_up_pressed_zaz);
  init_symbol(&symbols[13u], "RL_currentFloor_every", SYM_RULE);
  init_symbol(&symbols[14u], "RL_currentFloor_every_1", SYM_RULE);
  init_symbol(&symbols[15u], "RL_floor_des_every", SYM_RULE);
  init_symbol(&symbols[16u], "RL_floor_des_every_1", SYM_RULE);
  init_symbol(&symbols[17u], "RL_floor_down_pressed_every", SYM_RULE);
  init_symbol(&symbols[18u], "RL_floor_down_pressed_every_1", SYM_RULE);
  init_symbol(&symbols[19u], "RL_floor_up_pressed_every", SYM_RULE);
  init_symbol(&symbols[20u], "RL_floor_up_pressed_every_1", SYM_RULE);
  init_symbol(&symbols[21u], "RL_test", SYM_RULE);
  init_symbol(&symbols[22u], "v__h2308", SYM_DEF, &DEF_v__h2308, 3u);
  init_symbol(&symbols[23u], "v__h3216", SYM_DEF, &DEF_v__h3216, 32u);
  init_symbol(&symbols[24u], "v__h399", SYM_DEF, &DEF_v__h399, 3u);
  init_symbol(&symbols[25u], "value__h3219", SYM_DEF, &DEF_value__h3219, 32u);
  init_symbol(&symbols[26u], "x__h3473", SYM_DEF, &DEF_x__h3473, 32u);
  init_symbol(&symbols[27u], "x__h3848", SYM_DEF, &DEF_x__h3848, 32u);
  init_symbol(&symbols[28u], "x_wget__h2171", SYM_DEF, &DEF_x_wget__h2171, 3u);
  init_symbol(&symbols[29u], "x_wget__h253", SYM_DEF, &DEF_x_wget__h253, 3u);
  init_symbol(&symbols[30u], "x_wget__h3042", SYM_DEF, &DEF_x_wget__h3042, 32u);
}


/* Rule actions */

void MOD_mkNextFloorUpStop::RL_floor_up_pressed_every()
{
  tUInt8 DEF_new_value__h360;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h318 = rand32();
  DEF_new_value__h360 = (tUInt8)((tUInt8)7u & DEF_v__h318);
  INST_floor_up_pressed_zaz.METH_wset(DEF_new_value__h360);
}

void MOD_mkNextFloorUpStop::RL_floor_up_pressed_every_1()
{
  DEF_x_wget__h253 = INST_floor_up_pressed_zaz.METH_wget();
  DEF_v__h399 = INST_floor_up_pressed_zaz.METH_whas() ? DEF_x_wget__h253 : (tUInt8)0u;
  INST_floor_up_pressed_ignore.METH_wset(DEF_v__h399);
}

void MOD_mkNextFloorUpStop::RL_floor_down_pressed_every()
{
  tUInt8 DEF_new_value__h1400;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h1358 = rand32();
  DEF_new_value__h1400 = (tUInt8)((tUInt8)7u & DEF_v__h1358);
  INST_floor_down_pressed_zaz.METH_wset(DEF_new_value__h1400);
}

void MOD_mkNextFloorUpStop::RL_floor_down_pressed_every_1()
{
  DEF_x_wget__h1301 = INST_floor_down_pressed_zaz.METH_wget();
  DEF_v__h1438 = INST_floor_down_pressed_zaz.METH_whas() ? DEF_x_wget__h1301 : (tUInt8)0u;
  INST_floor_down_pressed_ignore.METH_wset(DEF_v__h1438);
}

void MOD_mkNextFloorUpStop::RL_floor_des_every()
{
  tUInt8 DEF_new_value__h2270;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h2228 = rand32();
  DEF_new_value__h2270 = (tUInt8)((tUInt8)7u & DEF_v__h2228);
  INST_floor_des_zaz.METH_wset(DEF_new_value__h2270);
}

void MOD_mkNextFloorUpStop::RL_floor_des_every_1()
{
  DEF_x_wget__h2171 = INST_floor_des_zaz.METH_wget();
  DEF_v__h2308 = INST_floor_des_zaz.METH_whas() ? DEF_x_wget__h2171 : (tUInt8)0u;
  INST_floor_des_ignore.METH_wset(DEF_v__h2308);
}

void MOD_mkNextFloorUpStop::RL_currentFloor_every()
{
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    rand32();
    DEF_new_value__h3178 = rand32();
  }
  INST_currentFloor_zaz.METH_wset(DEF_new_value__h3178);
}

void MOD_mkNextFloorUpStop::RL_currentFloor_every_1()
{
  DEF_x_wget__h3042 = INST_currentFloor_zaz.METH_wget();
  DEF_value__h3219 = INST_currentFloor_zaz.METH_whas() ? DEF_x_wget__h3042 : 0u;
  DEF_v__h3216 = 2147483648u + DEF_value__h3219;
  INST_currentFloor_ignore.METH_wset(DEF_v__h3216);
}

void MOD_mkNextFloorUpStop::RL_test()
{
  tUInt32 DEF_x__h6921;
  tUInt32 DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d112;
  tUInt32 DEF_signed_IF_IF_IF_2147483648_PLUS_IF_currentFlo_ETC___d133;
  tUInt8 DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d102;
  tUInt8 DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d104;
  tUInt8 DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128;
  tUInt32 DEF_signed_IF_IF_2147483648_PLUS_IF_currentFloor__ETC___d132;
  tUInt32 DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d124;
  tUInt32 DEF_signed_IF_IF_IF_2147483648_PLUS_IF_currentFlo_ETC___d134;
  tUInt32 DEF_signed_0___d129;
  tUInt32 DEF_signed_1___d130;
  tUInt32 DEF_signed_2___d131;
  tUInt8 DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d115;
  tUInt8 DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d114;
  DEF_signed_2___d131 = 2u;
  DEF_signed_1___d130 = 1u;
  DEF_signed_0___d129 = 0u;
  DEF_x_wget__h3042 = INST_currentFloor_zaz.METH_wget();
  DEF_x__h3473 = INST_cycle.METH_read();
  DEF_x_wget__h2171 = INST_floor_des_zaz.METH_wget();
  DEF_x_wget__h1301 = INST_floor_down_pressed_zaz.METH_wget();
  DEF_x_wget__h253 = INST_floor_up_pressed_zaz.METH_wget();
  DEF_v__h1438 = INST_floor_down_pressed_zaz.METH_whas() ? DEF_x_wget__h1301 : (tUInt8)0u;
  DEF_v__h399 = INST_floor_up_pressed_zaz.METH_whas() ? DEF_x_wget__h253 : (tUInt8)0u;
  DEF_v__h2308 = INST_floor_des_zaz.METH_whas() ? DEF_x_wget__h2171 : (tUInt8)0u;
  DEF_value__h3219 = INST_currentFloor_zaz.METH_whas() ? DEF_x_wget__h3042 : 0u;
  DEF_v__h3216 = 2147483648u + DEF_value__h3219;
  DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32 = (tUInt8)(DEF_v__h3216 >> 31u);
  DEF_cycle_9_EQ_128___d31 = DEF_x__h3473 == 128u;
  DEF_cycle_9_EQ_0___d30 = DEF_x__h3473 == 0u;
  DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66 = (tUInt8)((tUInt8)1u & DEF_v__h399);
  DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48 = (tUInt8)((tUInt8)1u & DEF_v__h2308);
  DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45 = (tUInt8)((tUInt8)1u & (DEF_v__h2308 >> 1u));
  DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64 = (tUInt8)((tUInt8)1u & (DEF_v__h399 >> 1u));
  DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d114 = DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45 || DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64;
  DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d104 = (tUInt8)(DEF_v__h1438 >> 2u);
  DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42 = (tUInt8)(DEF_v__h2308 >> 2u);
  DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d115 = DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42 || DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d104;
  DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d102 = (tUInt8)((tUInt8)1u & (DEF_v__h1438 >> 1u));
  DEF_x__h3848 = DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32 ? -DEF_v__h3216 : DEF_v__h3216;
  DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35 = DEF_x__h3848 % 3u;
  DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37 = DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32 ? -DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35 : DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35;
  DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40 = (tUInt8)(DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37 >> 31u) ? -DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37 : DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37;
  DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41 = primSLE8(1u,
									  32u,
									  (tUInt32)(DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40),
									  32u,
									  2u);
  switch (DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40) {
  case 0u:
    DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d124 = DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48 || DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66 ? 0u : (DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d114 ? 1u : (DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d115 ? 2u : (DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d102 ? 1u : 0u)));
    break;
  case 1u:
    DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d124 = DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d114 ? 1u : (DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d115 ? 2u : 1u);
    break;
  default:
    DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d124 = 2u;
  }
  DEF_signed_IF_IF_IF_2147483648_PLUS_IF_currentFlo_ETC___d134 = DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d124;
  DEF_signed_IF_IF_2147483648_PLUS_IF_currentFloor__ETC___d132 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40;
  DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44 = primSLE8(1u,
									  32u,
									  (tUInt32)(DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40),
									  32u,
									  1u);
  DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52 = !DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44;
  DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d47 = primSLE8(1u,
									  32u,
									  (tUInt32)(DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40),
									  32u,
									  0u);
  DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d47 && DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48;
  DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d70 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d47 && DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66;
  DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d79 = !DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41;
  DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d65 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44 && DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64;
  DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d83 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d65 || DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d70;
  DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d55 = !DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d47;
  DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d57 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d55 || !DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48;
  DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d68 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d55 || !DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66;
  DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d72 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d65 && DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d68 ? 1u : (DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d70 ? 0u : DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40);
  DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d46 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44 && DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45;
  DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d43 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41 && DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42;
  DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d51 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d43 || (DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d46 || DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49);
  DEF_x__h6921 = DEF_x__h3473 + 1u;
  DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d58 = (DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52 || !DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45) && DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d57;
  DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d63 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d43 && DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d58 ? 2u : (DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d46 && DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d57 ? 1u : (DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49 ? 0u : DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40));
  DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d73 = primSLE8(1u,
									  32u,
									  (tUInt32)(DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d63),
									  32u,
									  (tUInt32)(DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d72));
  DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d78 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d51 && (DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d73 || ((DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52 || !DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64) && DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d68));
  DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d88 = (((DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d79 || !DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42) && DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d58) && DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d83) || ((DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d51 && DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d83) && !DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d73);
  DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d112 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d78 ? DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d63 : (DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d88 ? DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d72 : ((DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44 && DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d102) && (DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d79 || !DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d104) ? 1u : (DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41 && DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d104 ? 2u : DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40)));
  DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128 = !DEF_cycle_9_EQ_0___d30 && (!DEF_cycle_9_EQ_128___d31 && !(DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d112 == DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d124));
  DEF_signed_IF_IF_IF_2147483648_PLUS_IF_currentFlo_ETC___d133 = DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d112;
  if (DEF_cycle_9_EQ_0___d30)
    INST_floor_up_pressed_initialized.METH_write((tUInt8)1u);
  if (DEF_cycle_9_EQ_0___d30)
    INST_floor_down_pressed_initialized.METH_write((tUInt8)1u);
  if (DEF_cycle_9_EQ_0___d30)
    INST_floor_des_initialized.METH_write((tUInt8)1u);
  if (DEF_cycle_9_EQ_0___d30)
    INST_currentFloor_initialized.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_cycle_9_EQ_128___d31)
      dollar_display(sim_hdl, this, "s", &__str_literal_1);
    if (DEF_cycle_9_EQ_128___d31)
      dollar_finish(sim_hdl, "32", 1u);
    if (DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_2, DEF_x__h3473);
    if (DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,1",
		     &__str_literal_3,
		     DEF_signed_0___d129,
		     DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66);
    if (DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128)
      dollar_display(sim_hdl, this, "s,-32,1", &__str_literal_4, DEF_signed_0___d129, (tUInt8)0u);
    if (DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,1",
		     &__str_literal_5,
		     DEF_signed_0___d129,
		     DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48);
    if (DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,1",
		     &__str_literal_3,
		     DEF_signed_1___d130,
		     DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64);
    if (DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,1",
		     &__str_literal_4,
		     DEF_signed_1___d130,
		     DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d102);
    if (DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,1",
		     &__str_literal_5,
		     DEF_signed_1___d130,
		     DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45);
    if (DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128)
      dollar_display(sim_hdl, this, "s,-32,1", &__str_literal_3, DEF_signed_2___d131, (tUInt8)0u);
    if (DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,1",
		     &__str_literal_4,
		     DEF_signed_2___d131,
		     DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d104);
    if (DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,1",
		     &__str_literal_5,
		     DEF_signed_2___d131,
		     DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42);
    if (DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128)
      dollar_display(sim_hdl,
		     this,
		     "s,-32",
		     &__str_literal_6,
		     DEF_signed_IF_IF_2147483648_PLUS_IF_currentFloor__ETC___d132);
    if (DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32",
		     &__str_literal_7,
		     DEF_signed_IF_IF_IF_2147483648_PLUS_IF_currentFlo_ETC___d133,
		     DEF_signed_IF_IF_IF_2147483648_PLUS_IF_currentFlo_ETC___d134);
    if (DEF_NOT_cycle_9_EQ_0_0_00_AND_NOT_cycle_9_EQ_128_1_ETC___d128)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_cycle.METH_write(DEF_x__h6921);
}


/* Methods */


/* Reset routines */

void MOD_mkNextFloorUpStop::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_floor_up_pressed_initialized.reset_RST(ARG_rst_in);
  INST_floor_down_pressed_initialized.reset_RST(ARG_rst_in);
  INST_floor_des_initialized.reset_RST(ARG_rst_in);
  INST_cycle.reset_RST(ARG_rst_in);
  INST_currentFloor_initialized.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkNextFloorUpStop::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkNextFloorUpStop::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_currentFloor_ignore.dump_state(indent + 2u);
  INST_currentFloor_initialized.dump_state(indent + 2u);
  INST_currentFloor_zaz.dump_state(indent + 2u);
  INST_cycle.dump_state(indent + 2u);
  INST_floor_des_ignore.dump_state(indent + 2u);
  INST_floor_des_initialized.dump_state(indent + 2u);
  INST_floor_des_zaz.dump_state(indent + 2u);
  INST_floor_down_pressed_ignore.dump_state(indent + 2u);
  INST_floor_down_pressed_initialized.dump_state(indent + 2u);
  INST_floor_down_pressed_zaz.dump_state(indent + 2u);
  INST_floor_up_pressed_ignore.dump_state(indent + 2u);
  INST_floor_up_pressed_initialized.dump_state(indent + 2u);
  INST_floor_up_pressed_zaz.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkNextFloorUpStop::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 61u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d43", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d46", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d47", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d51", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d65", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d70", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d78", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d83", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d63", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d72", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d73", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d55", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d57", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d58", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d68", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d79", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d88", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_9_EQ_0___d30", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cycle_9_EQ_128___d31", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "new_value__h3178", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1358", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h1438", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h2228", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h2308", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h318", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h3216", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h399", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "value__h3219", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h3473", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h3848", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h1301", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h2171", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h253", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h3042", 32u);
  num = INST_currentFloor_ignore.dump_VCD_defs(num);
  num = INST_currentFloor_initialized.dump_VCD_defs(num);
  num = INST_currentFloor_zaz.dump_VCD_defs(num);
  num = INST_cycle.dump_VCD_defs(num);
  num = INST_floor_des_ignore.dump_VCD_defs(num);
  num = INST_floor_des_initialized.dump_VCD_defs(num);
  num = INST_floor_des_zaz.dump_VCD_defs(num);
  num = INST_floor_down_pressed_ignore.dump_VCD_defs(num);
  num = INST_floor_down_pressed_initialized.dump_VCD_defs(num);
  num = INST_floor_down_pressed_zaz.dump_VCD_defs(num);
  num = INST_floor_up_pressed_ignore.dump_VCD_defs(num);
  num = INST_floor_up_pressed_initialized.dump_VCD_defs(num);
  num = INST_floor_up_pressed_zaz.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkNextFloorUpStop::dump_VCD(tVCDDumpType dt,
				     unsigned int levels,
				     MOD_mkNextFloorUpStop &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkNextFloorUpStop::vcd_defs(tVCDDumpType dt, MOD_mkNextFloorUpStop &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 32u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35) != DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35, 32u);
	backing.DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35 = DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35;
      }
      ++num;
      if ((backing.DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37) != DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37, 32u);
	backing.DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37 = DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37;
      }
      ++num;
      if ((backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40) != DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40, 32u);
	backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40;
      }
      ++num;
      if ((backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41) != DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41, 1u);
	backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41;
      }
      ++num;
      if ((backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d43) != DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d43)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d43, 1u);
	backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d43 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d43;
      }
      ++num;
      if ((backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44) != DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44, 1u);
	backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44;
      }
      ++num;
      if ((backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d46) != DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d46)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d46, 1u);
	backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d46 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d46;
      }
      ++num;
      if ((backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d47) != DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d47)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d47, 1u);
	backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d47 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d47;
      }
      ++num;
      if ((backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49) != DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49, 1u);
	backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49;
      }
      ++num;
      if ((backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d51) != DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d51)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d51, 1u);
	backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d51 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d51;
      }
      ++num;
      if ((backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d65) != DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d65)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d65, 1u);
	backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d65 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d65;
      }
      ++num;
      if ((backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d70) != DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d70)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d70, 1u);
	backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d70 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d70;
      }
      ++num;
      if ((backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d78) != DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d78)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d78, 1u);
	backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d78 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d78;
      }
      ++num;
      if ((backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d83) != DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d83)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d83, 1u);
	backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d83 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d83;
      }
      ++num;
      if ((backing.DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d63) != DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d63)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d63, 32u);
	backing.DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d63 = DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d63;
      }
      ++num;
      if ((backing.DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d72) != DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d72)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d72, 32u);
	backing.DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d72 = DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d72;
      }
      ++num;
      if ((backing.DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d73) != DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d73)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d73, 1u);
	backing.DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d73 = DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d73;
      }
      ++num;
      if ((backing.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42) != DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42, 1u);
	backing.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42 = DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42;
      }
      ++num;
      if ((backing.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45) != DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45, 1u);
	backing.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45 = DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45;
      }
      ++num;
      if ((backing.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48) != DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48, 1u);
	backing.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48 = DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48;
      }
      ++num;
      if ((backing.DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64) != DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64, 1u);
	backing.DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64 = DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64;
      }
      ++num;
      if ((backing.DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66) != DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66, 1u);
	backing.DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66 = DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66;
      }
      ++num;
      if ((backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52) != DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52, 1u);
	backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52;
      }
      ++num;
      if ((backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d55) != DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d55)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d55, 1u);
	backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d55 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d55;
      }
      ++num;
      if ((backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d57) != DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d57)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d57, 1u);
	backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d57 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d57;
      }
      ++num;
      if ((backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d58) != DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d58)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d58, 1u);
	backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d58 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d58;
      }
      ++num;
      if ((backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d68) != DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d68)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d68, 1u);
	backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d68 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d68;
      }
      ++num;
      if ((backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d79) != DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d79)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d79, 1u);
	backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d79 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d79;
      }
      ++num;
      if ((backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d88) != DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d88)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d88, 1u);
	backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d88 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d88;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32) != DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32)
      {
	vcd_write_val(sim_hdl, num, DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32, 1u);
	backing.DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32 = DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32;
      }
      ++num;
      if ((backing.DEF_cycle_9_EQ_0___d30) != DEF_cycle_9_EQ_0___d30)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_9_EQ_0___d30, 1u);
	backing.DEF_cycle_9_EQ_0___d30 = DEF_cycle_9_EQ_0___d30;
      }
      ++num;
      if ((backing.DEF_cycle_9_EQ_128___d31) != DEF_cycle_9_EQ_128___d31)
      {
	vcd_write_val(sim_hdl, num, DEF_cycle_9_EQ_128___d31, 1u);
	backing.DEF_cycle_9_EQ_128___d31 = DEF_cycle_9_EQ_128___d31;
      }
      ++num;
      if ((backing.DEF_new_value__h3178) != DEF_new_value__h3178)
      {
	vcd_write_val(sim_hdl, num, DEF_new_value__h3178, 32u);
	backing.DEF_new_value__h3178 = DEF_new_value__h3178;
      }
      ++num;
      if ((backing.DEF_v__h1358) != DEF_v__h1358)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1358, 32u);
	backing.DEF_v__h1358 = DEF_v__h1358;
      }
      ++num;
      if ((backing.DEF_v__h1438) != DEF_v__h1438)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h1438, 3u);
	backing.DEF_v__h1438 = DEF_v__h1438;
      }
      ++num;
      if ((backing.DEF_v__h2228) != DEF_v__h2228)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h2228, 32u);
	backing.DEF_v__h2228 = DEF_v__h2228;
      }
      ++num;
      if ((backing.DEF_v__h2308) != DEF_v__h2308)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h2308, 3u);
	backing.DEF_v__h2308 = DEF_v__h2308;
      }
      ++num;
      if ((backing.DEF_v__h318) != DEF_v__h318)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h318, 32u);
	backing.DEF_v__h318 = DEF_v__h318;
      }
      ++num;
      if ((backing.DEF_v__h3216) != DEF_v__h3216)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h3216, 32u);
	backing.DEF_v__h3216 = DEF_v__h3216;
      }
      ++num;
      if ((backing.DEF_v__h399) != DEF_v__h399)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h399, 3u);
	backing.DEF_v__h399 = DEF_v__h399;
      }
      ++num;
      if ((backing.DEF_value__h3219) != DEF_value__h3219)
      {
	vcd_write_val(sim_hdl, num, DEF_value__h3219, 32u);
	backing.DEF_value__h3219 = DEF_value__h3219;
      }
      ++num;
      if ((backing.DEF_x__h3473) != DEF_x__h3473)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h3473, 32u);
	backing.DEF_x__h3473 = DEF_x__h3473;
      }
      ++num;
      if ((backing.DEF_x__h3848) != DEF_x__h3848)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h3848, 32u);
	backing.DEF_x__h3848 = DEF_x__h3848;
      }
      ++num;
      if ((backing.DEF_x_wget__h1301) != DEF_x_wget__h1301)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h1301, 3u);
	backing.DEF_x_wget__h1301 = DEF_x_wget__h1301;
      }
      ++num;
      if ((backing.DEF_x_wget__h2171) != DEF_x_wget__h2171)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h2171, 3u);
	backing.DEF_x_wget__h2171 = DEF_x_wget__h2171;
      }
      ++num;
      if ((backing.DEF_x_wget__h253) != DEF_x_wget__h253)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h253, 3u);
	backing.DEF_x_wget__h253 = DEF_x_wget__h253;
      }
      ++num;
      if ((backing.DEF_x_wget__h3042) != DEF_x_wget__h3042)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h3042, 32u);
	backing.DEF_x_wget__h3042 = DEF_x_wget__h3042;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35, 32u);
      backing.DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35 = DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35;
      vcd_write_val(sim_hdl, num++, DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37, 32u);
      backing.DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37 = DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40, 32u);
      backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41, 1u);
      backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d43, 1u);
      backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d43 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d43;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44, 1u);
      backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d44;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d46, 1u);
      backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d46 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d46;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d47, 1u);
      backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d47 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d47;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49, 1u);
      backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d51, 1u);
      backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d51 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d51;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d65, 1u);
      backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d65 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d65;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d70, 1u);
      backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d70 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d70;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d78, 1u);
      backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d78 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d78;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d83, 1u);
      backing.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d83 = DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d83;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d63, 32u);
      backing.DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d63 = DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d63;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d72, 32u);
      backing.DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d72 = DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d72;
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d73, 1u);
      backing.DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d73 = DEF_IF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_w_ETC___d73;
      vcd_write_val(sim_hdl, num++, DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42, 1u);
      backing.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42 = DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d42;
      vcd_write_val(sim_hdl, num++, DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45, 1u);
      backing.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45 = DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d45;
      vcd_write_val(sim_hdl, num++, DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48, 1u);
      backing.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48 = DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d48;
      vcd_write_val(sim_hdl, num++, DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64, 1u);
      backing.DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64 = DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d64;
      vcd_write_val(sim_hdl, num++, DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66, 1u);
      backing.DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66 = DEF_IF_floor_up_pressed_zaz_whas_THEN_floor_up_pre_ETC___d66;
      vcd_write_val(sim_hdl, num++, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52, 1u);
      backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52;
      vcd_write_val(sim_hdl, num++, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d55, 1u);
      backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d55 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d55;
      vcd_write_val(sim_hdl, num++, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d57, 1u);
      backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d57 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d57;
      vcd_write_val(sim_hdl, num++, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d58, 1u);
      backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d58 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d58;
      vcd_write_val(sim_hdl, num++, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d68, 1u);
      backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d68 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d68;
      vcd_write_val(sim_hdl, num++, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d79, 1u);
      backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d79 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d79;
      vcd_write_val(sim_hdl, num++, DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d88, 1u);
      backing.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d88 = DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d88;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32, 1u);
      backing.DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32 = DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32;
      vcd_write_val(sim_hdl, num++, DEF_cycle_9_EQ_0___d30, 1u);
      backing.DEF_cycle_9_EQ_0___d30 = DEF_cycle_9_EQ_0___d30;
      vcd_write_val(sim_hdl, num++, DEF_cycle_9_EQ_128___d31, 1u);
      backing.DEF_cycle_9_EQ_128___d31 = DEF_cycle_9_EQ_128___d31;
      vcd_write_val(sim_hdl, num++, DEF_new_value__h3178, 32u);
      backing.DEF_new_value__h3178 = DEF_new_value__h3178;
      vcd_write_val(sim_hdl, num++, DEF_v__h1358, 32u);
      backing.DEF_v__h1358 = DEF_v__h1358;
      vcd_write_val(sim_hdl, num++, DEF_v__h1438, 3u);
      backing.DEF_v__h1438 = DEF_v__h1438;
      vcd_write_val(sim_hdl, num++, DEF_v__h2228, 32u);
      backing.DEF_v__h2228 = DEF_v__h2228;
      vcd_write_val(sim_hdl, num++, DEF_v__h2308, 3u);
      backing.DEF_v__h2308 = DEF_v__h2308;
      vcd_write_val(sim_hdl, num++, DEF_v__h318, 32u);
      backing.DEF_v__h318 = DEF_v__h318;
      vcd_write_val(sim_hdl, num++, DEF_v__h3216, 32u);
      backing.DEF_v__h3216 = DEF_v__h3216;
      vcd_write_val(sim_hdl, num++, DEF_v__h399, 3u);
      backing.DEF_v__h399 = DEF_v__h399;
      vcd_write_val(sim_hdl, num++, DEF_value__h3219, 32u);
      backing.DEF_value__h3219 = DEF_value__h3219;
      vcd_write_val(sim_hdl, num++, DEF_x__h3473, 32u);
      backing.DEF_x__h3473 = DEF_x__h3473;
      vcd_write_val(sim_hdl, num++, DEF_x__h3848, 32u);
      backing.DEF_x__h3848 = DEF_x__h3848;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h1301, 3u);
      backing.DEF_x_wget__h1301 = DEF_x_wget__h1301;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h2171, 3u);
      backing.DEF_x_wget__h2171 = DEF_x_wget__h2171;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h253, 3u);
      backing.DEF_x_wget__h253 = DEF_x_wget__h253;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h3042, 32u);
      backing.DEF_x_wget__h3042 = DEF_x_wget__h3042;
    }
}

void MOD_mkNextFloorUpStop::vcd_prims(tVCDDumpType dt, MOD_mkNextFloorUpStop &backing)
{
  INST_currentFloor_ignore.dump_VCD(dt, backing.INST_currentFloor_ignore);
  INST_currentFloor_initialized.dump_VCD(dt, backing.INST_currentFloor_initialized);
  INST_currentFloor_zaz.dump_VCD(dt, backing.INST_currentFloor_zaz);
  INST_cycle.dump_VCD(dt, backing.INST_cycle);
  INST_floor_des_ignore.dump_VCD(dt, backing.INST_floor_des_ignore);
  INST_floor_des_initialized.dump_VCD(dt, backing.INST_floor_des_initialized);
  INST_floor_des_zaz.dump_VCD(dt, backing.INST_floor_des_zaz);
  INST_floor_down_pressed_ignore.dump_VCD(dt, backing.INST_floor_down_pressed_ignore);
  INST_floor_down_pressed_initialized.dump_VCD(dt, backing.INST_floor_down_pressed_initialized);
  INST_floor_down_pressed_zaz.dump_VCD(dt, backing.INST_floor_down_pressed_zaz);
  INST_floor_up_pressed_ignore.dump_VCD(dt, backing.INST_floor_up_pressed_ignore);
  INST_floor_up_pressed_initialized.dump_VCD(dt, backing.INST_floor_up_pressed_initialized);
  INST_floor_up_pressed_zaz.dump_VCD(dt, backing.INST_floor_up_pressed_zaz);
}
