/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Mon Mar  6 22:44:25 PST 2017
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkNextFloorDownStop.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkNextFloorDownStop::MODEL_mkNextFloorDownStop()
{
  mkNextFloorDownStop_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkNextFloorDownStop()
{
  MODEL_mkNextFloorDownStop *model = new MODEL_mkNextFloorDownStop();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkNextFloorDownStop &INST_top = *((MOD_mkNextFloorDownStop *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_floor_up_pressed_initialized__h393;
	 tUInt8 DEF_INST_top_DEF_floor_down_pressed_initialized__h1432;
	 tUInt8 DEF_INST_top_DEF_floor_des_initialized__h2302;
	 tUInt8 DEF_INST_top_DEF_currentFloor_initialized___d23;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_floor_up_pressed_every;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_floor_up_pressed_every;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_floor_up_pressed_every_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_floor_up_pressed_every_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_floor_down_pressed_every;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_floor_down_pressed_every;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_floor_down_pressed_every_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_floor_down_pressed_every_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_floor_des_every;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_floor_des_every;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_floor_des_every_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_floor_des_every_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_currentFloor_every;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_currentFloor_every;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_currentFloor_every_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_currentFloor_every_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_test;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_test;
	 DEF_INST_top_DEF_CAN_FIRE_RL_currentFloor_every = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_currentFloor_every = DEF_INST_top_DEF_CAN_FIRE_RL_currentFloor_every;
	 DEF_INST_top_DEF_currentFloor_initialized___d23 = INST_top.INST_currentFloor_initialized.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_currentFloor_every_1 = !DEF_INST_top_DEF_currentFloor_initialized___d23;
	 DEF_INST_top_DEF_WILL_FIRE_RL_currentFloor_every_1 = DEF_INST_top_DEF_CAN_FIRE_RL_currentFloor_every_1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_floor_des_every = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_floor_des_every = DEF_INST_top_DEF_CAN_FIRE_RL_floor_des_every;
	 DEF_INST_top_DEF_floor_des_initialized__h2302 = INST_top.INST_floor_des_initialized.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_floor_des_every_1 = !DEF_INST_top_DEF_floor_des_initialized__h2302;
	 DEF_INST_top_DEF_WILL_FIRE_RL_floor_des_every_1 = DEF_INST_top_DEF_CAN_FIRE_RL_floor_des_every_1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_floor_down_pressed_every = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_floor_down_pressed_every = DEF_INST_top_DEF_CAN_FIRE_RL_floor_down_pressed_every;
	 DEF_INST_top_DEF_floor_down_pressed_initialized__h1432 = INST_top.INST_floor_down_pressed_initialized.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_floor_down_pressed_every_1 = !DEF_INST_top_DEF_floor_down_pressed_initialized__h1432;
	 DEF_INST_top_DEF_WILL_FIRE_RL_floor_down_pressed_every_1 = DEF_INST_top_DEF_CAN_FIRE_RL_floor_down_pressed_every_1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_floor_up_pressed_every = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_floor_up_pressed_every = DEF_INST_top_DEF_CAN_FIRE_RL_floor_up_pressed_every;
	 DEF_INST_top_DEF_floor_up_pressed_initialized__h393 = INST_top.INST_floor_up_pressed_initialized.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_floor_up_pressed_every_1 = !DEF_INST_top_DEF_floor_up_pressed_initialized__h393;
	 DEF_INST_top_DEF_WILL_FIRE_RL_floor_up_pressed_every_1 = DEF_INST_top_DEF_CAN_FIRE_RL_floor_up_pressed_every_1;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_floor_up_pressed_every)
	   INST_top.RL_floor_up_pressed_every();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_floor_down_pressed_every)
	   INST_top.RL_floor_down_pressed_every();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_floor_des_every)
	   INST_top.RL_floor_des_every();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_currentFloor_every)
	   INST_top.RL_currentFloor_every();
	 INST_top.DEF_x_wget__h3042 = INST_top.INST_currentFloor_zaz.METH_wget();
	 INST_top.DEF_x__h3473 = INST_top.INST_cycle.METH_read();
	 INST_top.DEF_x_wget__h2171 = INST_top.INST_floor_des_zaz.METH_wget();
	 INST_top.DEF_x_wget__h1301 = INST_top.INST_floor_down_pressed_zaz.METH_wget();
	 INST_top.DEF_v__h1438 = INST_top.INST_floor_down_pressed_zaz.METH_whas() ? INST_top.DEF_x_wget__h1301 : (tUInt8)0u;
	 INST_top.DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d67 = (tUInt8)((INST_top.DEF_v__h1438) >> 2u);
	 INST_top.DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d65 = (tUInt8)((tUInt8)1u & ((INST_top.DEF_v__h1438) >> 1u));
	 INST_top.DEF_v__h2308 = INST_top.INST_floor_des_zaz.METH_whas() ? INST_top.DEF_x_wget__h2171 : (tUInt8)0u;
	 INST_top.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d51 = (tUInt8)((INST_top.DEF_v__h2308) >> 2u);
	 INST_top.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d47 = (tUInt8)((tUInt8)1u & ((INST_top.DEF_v__h2308) >> 1u));
	 INST_top.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d43 = (tUInt8)((tUInt8)1u & (INST_top.DEF_v__h2308));
	 INST_top.DEF_value__h3219 = INST_top.INST_currentFloor_zaz.METH_whas() ? INST_top.DEF_x_wget__h3042 : 0u;
	 INST_top.DEF_v__h3216 = 2147483648u + (INST_top.DEF_value__h3219);
	 INST_top.DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32 = (tUInt8)((INST_top.DEF_v__h3216) >> 31u);
	 INST_top.DEF_x__h3847 = INST_top.DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32 ? -(INST_top.DEF_v__h3216) : INST_top.DEF_v__h3216;
	 INST_top.DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35 = (INST_top.DEF_x__h3847) % 3u;
	 INST_top.DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37 = INST_top.DEF__2147483648_PLUS_IF_currentFloor_zaz_whas__5_TH_ETC___d32 ? -(INST_top.DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35) : INST_top.DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d35;
	 INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40 = (tUInt8)((INST_top.DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37) >> 31u) ? -(INST_top.DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37) : INST_top.DEF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas__5_ETC___d37;
	 INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41 = (tUInt8)((INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40) >> 31u);
	 INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d45 = primSLT8(1u,
											  32u,
											  (tUInt32)(INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40),
											  32u,
											  1u);
	 INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49 = primSLT8(1u,
											  32u,
											  (tUInt32)(INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40),
											  32u,
											  2u);
	 INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d58 = INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49 || !(INST_top.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d51);
	 INST_top.DEF_cycle_9_EQ_128___d31 = (INST_top.DEF_x__h3473) == 128u;
	 INST_top.DEF_cycle_9_EQ_0___d30 = (INST_top.DEF_x__h3473) == 0u;
	 INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d69 = INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49 || !(INST_top.DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d67);
	 INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d59 = (INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d45 || !(INST_top.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d47)) && INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d58;
	 INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d42 = !(INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41);
	 INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d44 = INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d42 && INST_top.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d43;
	 INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d50 = !(INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d49);
	 INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d71 = INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d50 && INST_top.DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d67;
	 INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52 = INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d50 && INST_top.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d51;
	 INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d46 = !(INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d45);
	 INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d66 = INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d46 && INST_top.DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d65;
	 INST_top.DEF_IF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_z_ETC___d73 = INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d66 && INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d69 ? 1u : (INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d71 ? 2u : INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40);
	 INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d84 = INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d66 || INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d71;
	 INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d48 = INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d46 && INST_top.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d47;
	 INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d54 = INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d44 || (INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d48 || INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52);
	 INST_top.DEF_IF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_z_ETC___d64 = INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d44 && INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d59 ? 0u : (INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d48 && INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d58 ? 1u : (INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d52 ? 2u : INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40));
	 INST_top.DEF_IF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_z_ETC___d74 = primSLT8(1u,
											  32u,
											  (tUInt32)(INST_top.DEF_IF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_z_ETC___d64),
											  32u,
											  (tUInt32)(INST_top.DEF_IF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_z_ETC___d73));
	 INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d88 = (((INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d41 || !(INST_top.DEF_IF_floor_des_zaz_whas__9_THEN_floor_des_zaz_wg_ETC___d43)) && INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d59) && INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d84) || ((INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d54 && INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d84) && INST_top.DEF_IF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_z_ETC___d74);
	 INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d80 = INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d54 && (!(INST_top.DEF_IF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_z_ETC___d74) || ((INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d45 || !(INST_top.DEF_IF_floor_down_pressed_zaz_whas__2_THEN_floor_d_ETC___d65)) && INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d69));
	 DEF_INST_top_DEF_CAN_FIRE_RL_test = INST_top.DEF_cycle_9_EQ_0___d30 || (INST_top.DEF_cycle_9_EQ_128___d31 || (DEF_INST_top_DEF_floor_up_pressed_initialized__h393 && (DEF_INST_top_DEF_floor_down_pressed_initialized__h1432 && (DEF_INST_top_DEF_floor_des_initialized__h2302 && (DEF_INST_top_DEF_currentFloor_initialized___d23 && ((INST_top.DEF_NOT_IF_IF_2147483648_PLUS_IF_currentFloor_zaz__ETC___d80 || (INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d88 ? DEF_INST_top_DEF_floor_down_pressed_initialized__h1432 : DEF_INST_top_DEF_floor_up_pressed_initialized__h393)) && ((INST_top.DEF_IF_IF_2147483648_PLUS_IF_currentFloor_zaz_whas_ETC___d40) == 2u ? DEF_INST_top_DEF_floor_des_initialized__h2302 : DEF_INST_top_DEF_currentFloor_initialized___d23)))))));
	 DEF_INST_top_DEF_WILL_FIRE_RL_test = DEF_INST_top_DEF_CAN_FIRE_RL_test;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_currentFloor_every_1)
	   INST_top.RL_currentFloor_every_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_floor_des_every_1)
	   INST_top.RL_floor_des_every_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_floor_down_pressed_every_1)
	   INST_top.RL_floor_down_pressed_every_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_floor_up_pressed_every_1)
	   INST_top.RL_floor_up_pressed_every_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_test)
	   INST_top.RL_test();
	 INST_top.INST_currentFloor_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_currentFloor_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_floor_des_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_floor_des_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_floor_down_pressed_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_floor_down_pressed_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_floor_up_pressed_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_floor_up_pressed_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_cycle.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_floor_up_pressed_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_floor_down_pressed_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_floor_des_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_currentFloor_initialized.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkNextFloorDownStop::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkNextFloorDownStop_instance = new MOD_mkNextFloorDownStop(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkNextFloorDownStop_instance->INST_floor_up_pressed_ignore.set_clk_0)("CLK");
  (mkNextFloorDownStop_instance->INST_floor_up_pressed_zaz.set_clk_0)("CLK");
  (mkNextFloorDownStop_instance->INST_floor_down_pressed_ignore.set_clk_0)("CLK");
  (mkNextFloorDownStop_instance->INST_floor_down_pressed_zaz.set_clk_0)("CLK");
  (mkNextFloorDownStop_instance->INST_floor_des_ignore.set_clk_0)("CLK");
  (mkNextFloorDownStop_instance->INST_floor_des_zaz.set_clk_0)("CLK");
  (mkNextFloorDownStop_instance->INST_currentFloor_ignore.set_clk_0)("CLK");
  (mkNextFloorDownStop_instance->INST_currentFloor_zaz.set_clk_0)("CLK");
  (mkNextFloorDownStop_instance->set_clk_0)("CLK");
}
void MODEL_mkNextFloorDownStop::destroy_model()
{
  delete mkNextFloorDownStop_instance;
  mkNextFloorDownStop_instance = NULL;
}
void MODEL_mkNextFloorDownStop::reset_model(bool asserted)
{
  (mkNextFloorDownStop_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkNextFloorDownStop::get_instance()
{
  return mkNextFloorDownStop_instance;
}

/* Fill in version numbers */
void MODEL_mkNextFloorDownStop::get_version(unsigned int *year,
					    unsigned int *month,
					    char const **annotation,
					    char const **build)
{
  *year = 2016u;
  *month = 7u;
  *annotation = "beta1";
  *build = "34806";
}

/* Get the model creation time */
time_t MODEL_mkNextFloorDownStop::get_creation_time()
{
  
  /* Tue Mar  7 06:44:25 UTC 2017 */
  return 1488869065llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mkNextFloorDownStop::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mkNextFloorDownStop::dump_state()
{
  (mkNextFloorDownStop_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkNextFloorDownStop & mkNextFloorDownStop_backing(tSimStateHdl simHdl)
{
  static MOD_mkNextFloorDownStop *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkNextFloorDownStop(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkNextFloorDownStop::dump_VCD_defs()
{
  (mkNextFloorDownStop_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkNextFloorDownStop::dump_VCD(tVCDDumpType dt)
{
  (mkNextFloorDownStop_instance->dump_VCD)(dt,
					   vcd_depth(sim_hdl),
					   mkNextFloorDownStop_backing(sim_hdl));
}
