/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Thu Mar  9 21:05:03 PST 2017
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkNextFloorStop.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkNextFloorStop::MODEL_mkNextFloorStop()
{
  mkNextFloorStop_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkNextFloorStop()
{
  MODEL_mkNextFloorStop *model = new MODEL_mkNextFloorStop();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkNextFloorStop &INST_top = *((MOD_mkNextFloorStop *)(instance_ptr));
	 tUInt8 DEF_INST_top_INST_testTb_DEF_floor_up_pressed_initialized__h389;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_floor_down_pressed_initialized__h1428;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_floor_des_initialized__h2298;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_currentFloor_initialized__h3207;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_direction_initialized__h3630;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_direction_every;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_direction_every;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_direction_every_1;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_direction_every_1;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_up_pressed_every;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_up_pressed_every;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_up_pressed_every_1;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_up_pressed_every_1;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_down_pressed_every;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_down_pressed_every;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_down_pressed_every_1;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_down_pressed_every_1;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_des_every;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_des_every;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_des_every_1;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_des_every_1;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_currentFloor_every;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_currentFloor_every;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_currentFloor_every_1;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_currentFloor_every_1;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_test;
	 tUInt8 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_test;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_test;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_test;
	 INST_top.DEF_x__h136 = INST_top.INST_cycle.METH_read();
	 INST_top.DEF_cycle_EQ_128___d3 = (INST_top.DEF_x__h136) == 128u;
	 INST_top.DEF_cycle_EQ_0___d2 = (INST_top.DEF_x__h136) == 0u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_test = INST_top.DEF_cycle_EQ_0___d2 || (INST_top.DEF_cycle_EQ_128___d3 || INST_top.INST_testTb.METH_RDY_getObj());
	 DEF_INST_top_DEF_WILL_FIRE_RL_test = DEF_INST_top_DEF_CAN_FIRE_RL_test;
	 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_currentFloor_every = (tUInt8)1u;
	 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_currentFloor_every = DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_currentFloor_every;
	 DEF_INST_top_INST_testTb_DEF_currentFloor_initialized__h3207 = INST_top.INST_testTb.INST_currentFloor_initialized.METH_read();
	 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_currentFloor_every_1 = !DEF_INST_top_INST_testTb_DEF_currentFloor_initialized__h3207;
	 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_currentFloor_every_1 = DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_currentFloor_every_1;
	 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_direction_every = (tUInt8)1u;
	 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_direction_every = DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_direction_every;
	 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_des_every = (tUInt8)1u;
	 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_des_every = DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_des_every;
	 DEF_INST_top_INST_testTb_DEF_direction_initialized__h3630 = INST_top.INST_testTb.INST_direction_initialized.METH_read();
	 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_direction_every_1 = !DEF_INST_top_INST_testTb_DEF_direction_initialized__h3630;
	 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_direction_every_1 = DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_direction_every_1;
	 DEF_INST_top_INST_testTb_DEF_floor_des_initialized__h2298 = INST_top.INST_testTb.INST_floor_des_initialized.METH_read();
	 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_des_every_1 = !DEF_INST_top_INST_testTb_DEF_floor_des_initialized__h2298;
	 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_des_every_1 = DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_des_every_1;
	 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_down_pressed_every = (tUInt8)1u;
	 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_down_pressed_every = DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_down_pressed_every;
	 DEF_INST_top_INST_testTb_DEF_floor_down_pressed_initialized__h1428 = INST_top.INST_testTb.INST_floor_down_pressed_initialized.METH_read();
	 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_down_pressed_every_1 = !DEF_INST_top_INST_testTb_DEF_floor_down_pressed_initialized__h1428;
	 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_down_pressed_every_1 = DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_down_pressed_every_1;
	 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_up_pressed_every = (tUInt8)1u;
	 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_up_pressed_every = DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_up_pressed_every;
	 INST_top.INST_testTb.DEF_x__h3971 = INST_top.INST_testTb.INST_cycle.METH_read();
	 INST_top.INST_testTb.DEF_cycle_6_EQ_128___d38 = (INST_top.INST_testTb.DEF_x__h3971) == 128u;
	 DEF_INST_top_INST_testTb_DEF_floor_up_pressed_initialized__h389 = INST_top.INST_testTb.INST_floor_up_pressed_initialized.METH_read();
	 INST_top.INST_testTb.DEF_cycle_6_EQ_0___d37 = (INST_top.INST_testTb.DEF_x__h3971) == 0u;
	 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_test = INST_top.INST_testTb.DEF_cycle_6_EQ_0___d37 || (INST_top.INST_testTb.DEF_cycle_6_EQ_128___d38 || (DEF_INST_top_INST_testTb_DEF_floor_up_pressed_initialized__h389 && (DEF_INST_top_INST_testTb_DEF_floor_down_pressed_initialized__h1428 && (DEF_INST_top_INST_testTb_DEF_floor_des_initialized__h2298 && (DEF_INST_top_INST_testTb_DEF_currentFloor_initialized__h3207 && (DEF_INST_top_INST_testTb_DEF_direction_initialized__h3630 && INST_top.INST_testTb.INST_outFIFO.METH_i_notFull()))))));
	 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_test = DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_test;
	 DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_up_pressed_every_1 = !DEF_INST_top_INST_testTb_DEF_floor_up_pressed_initialized__h389;
	 DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_up_pressed_every_1 = DEF_INST_top_INST_testTb_DEF_CAN_FIRE_RL_floor_up_pressed_every_1;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_test)
	   INST_top.RL_test();
	 if (DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_up_pressed_every)
	   INST_top.INST_testTb.RL_floor_up_pressed_every();
	 if (DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_down_pressed_every)
	   INST_top.INST_testTb.RL_floor_down_pressed_every();
	 if (DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_des_every)
	   INST_top.INST_testTb.RL_floor_des_every();
	 if (DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_currentFloor_every)
	   INST_top.INST_testTb.RL_currentFloor_every();
	 if (DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_currentFloor_every_1)
	   INST_top.INST_testTb.RL_currentFloor_every_1();
	 if (DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_direction_every)
	   INST_top.INST_testTb.RL_direction_every();
	 if (DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_direction_every_1)
	   INST_top.INST_testTb.RL_direction_every_1();
	 if (DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_des_every_1)
	   INST_top.INST_testTb.RL_floor_des_every_1();
	 if (DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_down_pressed_every_1)
	   INST_top.INST_testTb.RL_floor_down_pressed_every_1();
	 if (DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_floor_up_pressed_every_1)
	   INST_top.INST_testTb.RL_floor_up_pressed_every_1();
	 if (DEF_INST_top_INST_testTb_DEF_WILL_FIRE_RL_test)
	   INST_top.INST_testTb.RL_test();
	 INST_top.INST_testTb.INST_direction_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_testTb.INST_direction_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_testTb.INST_currentFloor_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_testTb.INST_currentFloor_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_testTb.INST_floor_des_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_testTb.INST_floor_des_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_testTb.INST_floor_down_pressed_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_testTb.INST_floor_down_pressed_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_testTb.INST_floor_up_pressed_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_testTb.INST_floor_up_pressed_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_testTb.INST_cycle.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_testTb.INST_floor_up_pressed_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_testTb.INST_floor_down_pressed_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_testTb.INST_floor_des_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_testTb.INST_currentFloor_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_testTb.INST_direction_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_testTb.INST_outFIFO.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_cycle.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkNextFloorStop::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkNextFloorStop_instance = new MOD_mkNextFloorStop(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkNextFloorStop_instance->INST_testTb.INST_floor_up_pressed_ignore.set_clk_0)("CLK");
  (mkNextFloorStop_instance->INST_testTb.INST_floor_up_pressed_zaz.set_clk_0)("CLK");
  (mkNextFloorStop_instance->INST_testTb.INST_floor_down_pressed_ignore.set_clk_0)("CLK");
  (mkNextFloorStop_instance->INST_testTb.INST_floor_down_pressed_zaz.set_clk_0)("CLK");
  (mkNextFloorStop_instance->INST_testTb.INST_floor_des_ignore.set_clk_0)("CLK");
  (mkNextFloorStop_instance->INST_testTb.INST_floor_des_zaz.set_clk_0)("CLK");
  (mkNextFloorStop_instance->INST_testTb.INST_currentFloor_ignore.set_clk_0)("CLK");
  (mkNextFloorStop_instance->INST_testTb.INST_currentFloor_zaz.set_clk_0)("CLK");
  (mkNextFloorStop_instance->INST_testTb.INST_direction_ignore.set_clk_0)("CLK");
  (mkNextFloorStop_instance->INST_testTb.INST_direction_zaz.set_clk_0)("CLK");
  (mkNextFloorStop_instance->INST_testTb.INST_outFIFO.set_clk_0)("CLK");
  (mkNextFloorStop_instance->INST_testTb.set_clk_0)("CLK");
  (mkNextFloorStop_instance->set_clk_0)("CLK");
}
void MODEL_mkNextFloorStop::destroy_model()
{
  delete mkNextFloorStop_instance;
  mkNextFloorStop_instance = NULL;
}
void MODEL_mkNextFloorStop::reset_model(bool asserted)
{
  (mkNextFloorStop_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkNextFloorStop::get_instance()
{
  return mkNextFloorStop_instance;
}

/* Fill in version numbers */
void MODEL_mkNextFloorStop::get_version(unsigned int *year,
					unsigned int *month,
					char const **annotation,
					char const **build)
{
  *year = 2016u;
  *month = 7u;
  *annotation = "beta1";
  *build = "34806";
}

/* Get the model creation time */
time_t MODEL_mkNextFloorStop::get_creation_time()
{
  
  /* Fri Mar 10 05:05:03 UTC 2017 */
  return 1489122303llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mkNextFloorStop::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mkNextFloorStop::dump_state()
{
  (mkNextFloorStop_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkNextFloorStop & mkNextFloorStop_backing(tSimStateHdl simHdl)
{
  static MOD_mkNextFloorStop *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkNextFloorStop(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkNextFloorStop::dump_VCD_defs()
{
  (mkNextFloorStop_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkNextFloorStop::dump_VCD(tVCDDumpType dt)
{
  (mkNextFloorStop_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkNextFloorStop_backing(sim_hdl));
}
